Repository fomantic/Fomantic-UI, pull requests merged in 2018-11, with the labels that each got.

#229 [Icon] Fix icons alignment
  src/definitions/elements/icon.less
Labels: :art: CSS, :crystal_ball: Enhancement, :sleeping: SUI Issue

#232 [Item] Inverted Variant
  src/definitions/elements/list.less
  src/definitions/views/item.less
  src/themes/default/elements/list.variables
  src/themes/default/views/item.variables
Labels: :art: CSS, :crystal_ball: Enhancement, :eyes: Needs Reviewed, :triangular_ruler: Needs Doc Changes

#216 [Multi] Fixes some CSS lint issues
  src/definitions/collections/table.less
  src/definitions/elements/button.less
  src/definitions/elements/container.less
  src/definitions/elements/divider.less
  src/definitions/elements/header.less
  src/definitions/elements/list.less
  src/definitions/elements/segment.less
  src/definitions/elements/step.less
  src/definitions/modules/calendar.less
  src/definitions/modules/checkbox.less
  src/definitions/modules/dropdown.less
  src/definitions/modules/embed.less
  src/definitions/modules/modal.less
  src/definitions/modules/progress.less
  src/definitions/modules/shape.less
  src/definitions/modules/sidebar.less
  src/definitions/modules/toast.less
  src/definitions/views/card.less
  src/definitions/views/feed.less
Labels: :art: CSS, :eyes: Needs Reviewed

#237 feat(statistic): add stackable variation
  src/definitions/views/statistic.less
  src/themes/default/views/statistic.variables
Labels: :art: CSS, :crystal_ball: Enhancement, :eyes: Needs Reviewed, :triangular_ruler: Needs Doc Changes

#211 [Calendar] Add ability to disable specific date(s)
  src/definitions/modules/calendar.js
  src/definitions/modules/calendar.less
Labels: :crystal_ball: Enhancement, :eyes: Needs Reviewed, :scroll: JavaScript, :triangular_ruler: Needs Doc Changes

#202 [Popup] Add no javascript popup some new features
  src/definitions/modules/popup.less
Labels: :art: CSS, :crystal_ball: Enhancement, :triangular_ruler: Needs Doc Changes

#238 [Form] Dropdown width in form
  src/definitions/collections/form.less
Labels: :art: CSS, :bug: Confirmed Bug

#239 [Theme] Add brand colors and update some
  src/definitions/elements/button.less
  src/themes/default/globals/site.variables
Labels: :art: CSS, :crystal_ball: Enhancement, :eyes: Needs Reviewed, Discussion

#241 [Popup/Transition/Placeholder] Old Fix was disturbing Popup position calculations
  src/definitions/elements/placeholder.less
  src/definitions/modules/transition.less
Labels: :art: CSS, :bug: Confirmed Bug, :rotating_light: High Priority

#243 [Dropdown] Fix to make PR #189 and #190 work together (Menu list bubbling)
  src/definitions/modules/dropdown.js
Labels: :bug: Confirmed Bug, :rotating_light: High Priority, :scroll: JavaScript

#244 [Dropdown] Clearing user additions prevented Dropdown List
  src/definitions/modules/dropdown.js
Labels: :bug: Confirmed Bug, :scroll: JavaScript, :sleeping: SUI Issue

#246 [Dropdown] Prevent user selection
  src/definitions/modules/dropdown.less
Labels: :art: CSS, :bug: Confirmed Bug, :sleeping: SUI Issue

#248 [Placeholder] Respect a possible 'image icon' not occupying the same space
  src/definitions/elements/placeholder.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#250 [Dropdown] Suppress events on enter key with multiple allowAdditions
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#251 [Table] fix table wide vertical+text alignment
  src/definitions/collections/table.less
  src/themes/default/collections/table.variables
Labels: :sleeping: sui issue, :zap: enhancement, lang: CSS :art:

#252 Improve README consistency
  README.md
Labels: :page_facing_up: documents, :zap: enhancement

#179 [Build Tools] update to gulp4
  gulpfile.js
  package-lock.json
  package.json
  tasks/admin/components/create.js
  tasks/admin/components/init.js
  tasks/admin/components/update.js
  tasks/admin/distributions/create.js
  tasks/admin/distributions/init.js
  tasks/admin/distributions/update.js
  tasks/admin/publish.js
  tasks/admin/release.js
  tasks/build.js
  tasks/build/assets.js
  tasks/build/css.js
  tasks/build/javascript.js
  tasks/check-install.js
  tasks/clean.js
  tasks/collections/admin.js
  tasks/collections/build.js
  tasks/collections/docs.js
  tasks/collections/install.js
  tasks/collections/internal.js
  tasks/collections/rtl.js
  tasks/collections/various.js
  tasks/config/admin/github.js
  tasks/config/npm/gulpfile.js
  tasks/docs/build.js
  tasks/docs/serve.js
  tasks/install.js
  tasks/rtl/build.js
  tasks/rtl/watch.js
  tasks/version.js
  tasks/watch.js
Labels: :electric_plug: build tools, :eyes: needs reviewed

#253 [Table] images in tables did not display properly
  src/definitions/collections/table.less
Labels: :bug: confirmed bug, :sleeping: sui issue, lang: CSS :art:

#178 [Toast] Change default class for title to header
  src/definitions/modules/toast.js
  src/definitions/modules/toast.less
Labels: :bookmark_tabs: docs added, :hand: on hold, lang: CSS :art:, lang: JavaScript :scroll:

#197 [Toast] Use the same different color on every inverted toast
  src/definitions/modules/toast.less
  src/themes/default/modules/toast.variables
Labels: :zap: enhancement, lang: CSS :art:

#256 [Placeholder] Placeholder.less doesn't include placeholder.overrides
  src/definitions/elements/placeholder.less
Labels: :bug: confirmed bug, lang: CSS :art:

#230 [Label] Inverted Variant, basic grouping, basic tag, bugfixes
  src/definitions/collections/menu.less
  src/definitions/elements/label.less
  src/themes/default/elements/label.variables
  src/themes/default/globals/site.variables
Labels: :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:

#264 [Search] Wrap result into object when original result is received as array
  src/definitions/modules/search.js
Labels: :zap: enhancement, lang: JavaScript :scroll:

#269 fix(security): changed event-stream version
  package-lock.json
Labels: :electric_plug: build tools, :eyes: needs reviewed, priority: high :rotating_light:

#270 feat(input): add red border around `error labeled input`
  src/definitions/elements/input.less
Labels: :zap: enhancement, lang: CSS :art:
