Repository fomantic/Fomantic-UI, pull requests merged in 2018-10, with the labels that each got.

#133 [Icon] Comments icon inside "comment" component is not well aligned
  src/definitions/views/comment.less
  src/themes/chubby/views/comment.overrides
Labels: :art: CSS, :bug: Confirmed Bug, :eyes: Needs Reviewed

#136 [Modal] Fullscreen modals are not working in IE11
  src/definitions/modules/modal.less
Labels: :art: CSS, :bug: Confirmed Bug, :eyes: Needs Reviewed

#142 [Button] Simplify less code
  src/definitions/elements/button.less
Labels: :arrow_down: Low Priority, :art: CSS, :crystal_ball: Enhancement

#148 force display:none on .placeholder.hidden.transition
  src/definitions/modules/transition.less
Labels: :art: CSS, :bug: Confirmed Bug

#154 [Dropdown] Single Selection via keyboard gained focus again Fixes #153
  src/definitions/modules/dropdown.js
Labels: :bug: Confirmed Bug, :scroll: JavaScript

#155 [Dropdown] Fix the clearable setting that does'nt init a clearable dropdown
  src/definitions/modules/dropdown.js
Labels: :bug: Confirmed Bug, :scroll: JavaScript

#156 [Progress] Remove unused code
  src/definitions/modules/progress.js
Labels: :eyes: Needs Reviewed, :scroll: JavaScript, :wrench: refactor

#139 [Toast] Progressbar, closeEasing, Bugfixing, message support
  dist/components/toast.css
  dist/components/toast.js
  dist/components/transition.js
  src/definitions/modules/toast.js
  src/definitions/modules/toast.less
  src/definitions/modules/transition.js
  src/themes/default/modules/toast.variables
Labels: :art: CSS, :crystal_ball: Enhancement, :scroll: JavaScript, :triangular_ruler: Needs Doc Changes

#162 [Dimmer] Additional intensity states very light, light, medium
  src/definitions/modules/dimmer.less
  src/themes/default/modules/dimmer.variables
Labels: :art: CSS, :crystal_ball: Enhancement, :eyes: Needs Reviewed, :triangular_ruler: Needs Doc Changes

#161 [Form] Support inverted transparent textarea
  src/definitions/collections/form.less
Labels: :art: CSS, :crystal_ball: Enhancement

#163 [Form] Transparent Input/Textarea Error
  src/definitions/collections/form.less
  src/themes/default/collections/form.variables
Labels: :art: CSS, :crystal_ball: Enhancement

#157 [Modal] Inverted variant
  src/definitions/modules/modal.less
  src/themes/default/modules/modal.variables
Labels: :art: CSS, :crystal_ball: Enhancement, :eyes: Needs Reviewed, :triangular_ruler: Needs Doc Changes

#170 [Toast] Added SUI usual color palette with inverted support
  src/definitions/modules/toast.js
  src/definitions/modules/toast.less
Labels: :art: CSS, :crystal_ball: Enhancement, :eyes: Needs Reviewed, :scroll: JavaScript, :triangular_ruler: Needs Doc Changes

#164 [Progress] Improve performance for active progress bars
  src/definitions/modules/progress.less
Labels: :art: CSS, :crystal_ball: Enhancement, :eyes: Needs Reviewed

#168 [Icons] FontAwesome 5.4.1 update
  src/themes/default/assets/fonts/brand-icons.eot
  src/themes/default/assets/fonts/brand-icons.svg
  src/themes/default/assets/fonts/brand-icons.ttf
  src/themes/default/assets/fonts/brand-icons.woff
  src/themes/default/assets/fonts/brand-icons.woff2
  src/themes/default/assets/fonts/icons.eot
  src/themes/default/assets/fonts/icons.svg
  src/themes/default/assets/fonts/icons.ttf
  src/themes/default/assets/fonts/icons.woff
  src/themes/default/assets/fonts/icons.woff2
  src/themes/default/assets/fonts/outline-icons.eot
  src/themes/default/assets/fonts/outline-icons.ttf
  src/themes/default/assets/fonts/outline-icons.woff
  src/themes/default/assets/fonts/outline-icons.woff2
  src/themes/default/elements/icon.overrides
Labels: :art: CSS, :crystal_ball: Enhancement, :eyes: Needs Reviewed, Docs Added

#167 [Toast] fix position for top and bottom centered container
  src/definitions/modules/toast.less
Labels: :art: CSS, :bug: Confirmed Bug, :eyes: Needs Reviewed

#181 [Header] Top-attached headers missing top border
  src/definitions/elements/header.less
Labels: :art: CSS, :bug: Confirmed Bug, :eyes: Needs Reviewed

#183 [Icon] Fix group icon corner positions
  src/definitions/elements/icon.less
Labels: :art: CSS, :bug: Confirmed Bug, :eyes: Needs Reviewed

#185 chore: add vscode folder into .gitignore
  .gitignore
Labels: :crystal_ball: Enhancement, Platform

#187 [Dimmer] Fix content text color in inverted dimmer
  src/definitions/modules/dimmer.less
  src/themes/default/modules/dimmer.variables
Labels: :art: CSS, :crystal_ball: Enhancement

#195 [Dropdown] Prevent downshifting on multiselection
  src/definitions/modules/dropdown.less
Labels: :art: CSS, :bug: Confirmed Bug

#190 [Dropdown] Prevent close/open bubbling on keyselect via enter
  src/definitions/modules/dropdown.js
Labels: :bug: Confirmed Bug, :scroll: JavaScript

#188 [Dropdown] Stop Events after clicking outside of module
  src/definitions/modules/dropdown.js
Labels: :bug: Confirmed Bug, :eyes: Needs Reviewed, :scroll: JavaScript

#193 [Dropdown] showOnFocus:false prevented click to open dropdown
  src/definitions/modules/dropdown.js
Labels: :bug: Confirmed Bug, :eyes: Needs Reviewed, :scroll: JavaScript

#189 [Dropdown] Fix IE11 submenu selection triggered menu opening
  src/definitions/modules/dropdown.js
Labels: :bug: Confirmed Bug, :scroll: JavaScript

#196 [Progress] Display dark text on light inverted backgrounds
  src/themes/default/modules/progress.variables
Labels: :art: CSS, :crystal_ball: Enhancement, :eyes: Needs Reviewed

#199 [Calendar] Add ability to disable days of week
  src/definitions/modules/calendar.js
Labels: :crystal_ball: Enhancement, :eyes: Needs Reviewed, :scroll: JavaScript, :triangular_ruler: Needs Doc Changes

#186 [Dimmer] Added support for using dimmers only partially on top,center,bottom
  src/definitions/modules/dimmer.less
Labels: :art: CSS, :crystal_ball: Enhancement, :eyes: Needs Reviewed

#203 [Dropdown] Item of 'simple dropdown' in existing menus or 'simple floating' vanish preventing click
  src/definitions/modules/dropdown.less
Labels: :art: CSS, :bug: Confirmed Bug

#206 [Segment] Coloured inverted segments cannot be raised
  src/definitions/elements/segment.less
Labels: :art: CSS, :bug: Confirmed Bug

#209 [Modal] image content images can go out of content and description does not wrap
  src/definitions/modules/modal.less
Labels: :art: CSS, :bug: Confirmed Bug

#212 [Header] Fix corner icon size in icon header
  src/definitions/elements/header.less
  src/themes/default/elements/header.variables
Labels: :art: CSS, :bug: Confirmed Bug

#218 [menu] Dropdown inside menu should not reflect menu styling.
  src/definitions/collections/menu.less
Labels: :art: CSS, :bug: Confirmed Bug, :sleeping: SUI Issue

#224 [List] data-value on <div> list items is ignored
  src/definitions/elements/list.less
Labels: :art: CSS, :bug: Confirmed Bug, :sleeping: SUI Issue

#208 [Modal] Basic Modal and inverted modal on inverted dimmer had wrong close icon color
  src/definitions/modules/modal.less
  src/themes/default/modules/modal.variables
Labels: :art: CSS, :bug: Confirmed Bug, :eyes: Needs Reviewed

#31 Begin CI implementation
  .travis.yml
  preinstall.sh
Labels: :crystal_ball: Enhancement, :eyes: Needs Reviewed, :hammer: CI/CD, Discussion
