Repository fomantic/Fomantic-UI, pull requests merged in 2018-06, with the labels that each got.

#9 Fixlist
  src/definitions/elements/list.less
Labels: Can Merge

#11 [Flags] Fix wrong flag position for Myanmar / Burma
  src/themes/default/elements/flag.overrides
Labels: Can Merge

#12 [Dropdown] Adjust behavior of dropdown icon when search field is present
  src/definitions/modules/dropdown.js
Labels: Can Merge

#13 [Card] Icon containing class "card" misbehaves
  src/definitions/views/card.less
Labels: Can Merge

#10 Fixdimmer
  src/definitions/modules/dimmer.js
Labels: Can Merge

#16 [Form] IE11 - CSS rule is incorrect for input placeholders.
  src/definitions/collections/form.less
Labels: CSS, Can Merge

#17 [Dropdown] Only update text if action is activate or combo
  src/definitions/modules/dropdown.js
Labels: Can Merge, JavaScript

#18 [Dropdown] Only check option value to determine if option is selected
  src/definitions/modules/dropdown.js
Labels: Can Merge, JavaScript

#19 Fix last tab inside container which does not have correct bottom margin
  src/definitions/elements/segment.less
Labels: CSS, Can Merge

#23 [Table] Fix priority for td .disabled class
  src/definitions/collections/table.less
Labels: CSS, Can Merge

#26 [Form] Add * required marker from the label itself
  src/definitions/collections/form.less
Labels: CSS, Can Merge

#27 [Form Validation] Avoid trim of values before validation
  src/definitions/behaviors/form.js
Labels: Can Merge, Docs Added, JavaScript

#28 [Dropdown] Extend sortSelect with 'natural' and custom function
  src/definitions/modules/dropdown.js
Labels: Can Merge, Docs Added, JavaScript

#30 [Dropdown] Add new hideDividers option
  src/definitions/modules/dropdown.js
Labels: Can Merge, Docs Added, JavaScript

#25 [Dropdown] A fluid dropdown should be fluid
  src/definitions/modules/dropdown.less
Labels: CSS, Can Merge

#34 [Dropdown] Only select dividers if hideDividers option is true
  src/definitions/modules/dropdown.js
Labels: Confirmed Bug, High Priority, JavaScript

#36 [List] Typo in selection list item:hover selector
  src/definitions/elements/list.less
Labels: CSS, Can Merge
