Repository fomantic/Fomantic-UI, pull requests merged in 2018-09, with the labels that each got.

#103 [Accordion][Header] Header with content has display:none when in an accordion element
  src/definitions/modules/accordion.less
Labels: CSS, Confirmed Bug

#111 [Menu] Fix the inconsistent icon-text spacing in labeled icon menu dropdown
  src/definitions/collections/menu.less
Labels: CSS, Needs Reviewed

#113 [Calendar] Adds support for WeekNumbers in Day View
  dist/components/calendar.css
  dist/components/calendar.js
  src/definitions/modules/calendar.js
  src/definitions/modules/calendar.less
Labels: CSS, Enhancement, JavaScript, Needs Doc Changes, Needs Reviewed

#115 [Checkbox] since 2.5.0 'before[Un]Checked' fires already on init
  src/definitions/modules/checkbox.js
Labels: Confirmed Bug, JavaScript

#118 [Modal] Pressing the ESC key won't close all open modals anymore
  src/definitions/modules/modal.js
Labels: :crystal_ball: Enhancement, :eyes: Needs Reviewed, :scroll: JavaScript

#119 Lower modals are not accessible anymore in multiple modals
  src/definitions/modules/modal.js
Labels: :crystal_ball: Enhancement, :eyes: Needs Reviewed, :scroll: JavaScript

#120 Fixed some typos in the CONTRIBUTING guide
  CONTRIBUTING.md
Labels: :page_facing_up: Documents

#122 [Toast] Add a toast module
  src/definitions/globals/site.js
  src/definitions/modules/toast.js
  src/definitions/modules/toast.less
  src/semantic.less
  src/theme.config.example
  src/themes/default/modules/toast.overrides
  src/themes/default/modules/toast.variables
  tasks/config/admin/release.js
  tasks/config/defaults.js
  tasks/config/project/install.js
Labels: :art: CSS, :scroll: JavaScript, :triangular_ruler: Needs Doc Changes, UI Component

#124 [Message] Add floating variation to colored messages
  src/definitions/collections/message.less
  src/themes/default/collections/message.variables
Labels: :art: CSS, :bug: Confirmed Bug

#125 [Toast] Small fixes
  src/definitions/modules/toast.js
  src/definitions/modules/toast.less
Labels: :art: CSS, :scroll: JavaScript

#135 [Modal] Fullscreen modal stuck to left edge of page
  src/definitions/modules/modal.less
  src/themes/default/modules/modal.variables
Labels: :art: CSS, :bug: Confirmed Bug

#140 fixing both Bower and Composer package names
  bower.json
  composer.json
Labels: :crystal_ball: Enhancement, :electric_plug: Build Tools
