Repository fomantic/Fomantic-UI, pull requests merged in 2018-08, with the labels that each got.

#82 [Search] added ability to disable link action
  src/definitions/modules/search.js
  src/definitions/modules/search.less
Labels: CSS, Enhancement, JavaScript, Needs Doc Changes

#80 [Loader] Add color variants
  README.md
  src/definitions/elements/loader.less
Labels: CSS, Enhancement, Needs Doc Changes

#81 [Label] fixed incorrect label background color
  src/definitions/elements/label.less
  src/themes/default/elements/label.variables
Labels: CSS, Confirmed Bug, Needs Doc Changes

#71 Calendar
  RELEASE-NOTES.md
  src/definitions/globals/site.js
  src/definitions/modules/calendar.js
  src/definitions/modules/calendar.less
  src/semantic.less
  src/theme.config.example
  src/themes/default/modules/calendar.overrides
  src/themes/default/modules/calendar.variables
  tasks/config/admin/release.js
  tasks/config/defaults.js
  tasks/config/project/install.js
Labels: CSS, Discussion, Docs Added, Enhancement, JavaScript, UI Component

#83 [Search] set value inside onSelect callback
  src/definitions/modules/search.js
Labels: Confirmed Bug, JavaScript

#45 [Tab] Allow centered tab menu
  src/definitions/collections/menu.less
Labels: CSS, Enhancement, Needs Doc Changes

#87 [Flag] added uk as gb flag alias
  src/themes/default/elements/flag.overrides
Labels: CSS, Enhancement, Needs Doc Changes

#86 [Build Tools] changed from SUI repo to FUI
  tasks/config/project/release.js
Labels: Build Tools, Confirmed Bug

#85 [Checkbox] toggle don't have the "checked" class when initialized in a 'checked' state
  src/definitions/modules/checkbox.js
Labels: Confirmed Bug, JavaScript

#88 [Comment] Add `inverted` variation
  src/definitions/views/comment.less
Labels: CSS, Enhancement, Needs Doc Changes

#89 [Feed] Add `inverted` variation
  src/definitions/views/feed.less
Labels: CSS, Docs Added, Enhancement

#90 fix(accordion): Invert active condition
  src/definitions/modules/accordion.less
Labels: CSS, Confirmed Bug

#91 [Form] Added a transparent textarea option
  src/definitions/collections/form.less
Labels: CSS, Enhancement, Needs Doc Changes, Needs Reviewed

#92 [Step] Fix the bad step count in a segment
  src/definitions/elements/step.less
Labels: CSS

#93 [Step] Add `inverted` variation
  src/definitions/elements/step.less
  src/themes/default/elements/step.variables
Labels: CSS, Enhancement, Needs Doc Changes

#65 [Checkbox] Implements inverted mode for standalone checkboxes
  src/definitions/modules/checkbox.less
  src/themes/default/modules/checkbox.variables
Labels: CSS, Enhancement, Needs Doc Changes

#95 [Dropdown] Add ability to clear multiple selection dropdowns
  src/definitions/modules/dropdown.js
  src/definitions/modules/dropdown.less
Labels: CSS, Docs Added, Enhancement

#97 [Dependency] Fix compatibility issue with less >= 3.5 due to math changes
  src/definitions/collections/grid.less
  src/definitions/collections/menu.less
  src/definitions/modules/dropdown.less
  src/themes/default/collections/grid.variables
  src/themes/default/collections/menu.variables
  src/themes/default/collections/table.variables
  src/themes/default/elements/container.variables
  src/themes/default/elements/divider.variables
  src/themes/default/elements/label.variables
  src/themes/default/elements/rail.variables
  src/themes/default/elements/segment.variables
  src/themes/default/elements/step.variables
  src/themes/default/globals/site.variables
  src/themes/default/modules/dimmer.variables
  src/themes/default/modules/dropdown.variables
  src/themes/default/modules/popup.variables
  src/themes/default/modules/search.variables
  src/themes/default/views/card.variables
Labels: Build Tools, CSS, Confirmed Bug

#94 [Cards] add horizontal variation
  src/definitions/views/card.less
  src/themes/default/views/card.variables
Labels: CSS, Enhancement, Needs Doc Changes

#98 [Card] Add `inverted` variation
  src/definitions/views/card.less
  src/themes/default/views/card.variables
Labels: CSS, Docs Added, Enhancement

#99 [Grid] Add `compact` and `very compact` variations
  src/definitions/collections/grid.less
  src/themes/default/collections/grid.variables
Labels: CSS, Enhancement, Needs Doc Changes

#57 Implements dropdown different sizes (standalone and in forms)
  src/definitions/collections/form.less
  src/definitions/collections/menu.less
  src/definitions/elements/button.less
  src/definitions/modules/dropdown.less
Labels: CSS, Discussion, Docs Added, Enhancement, Needs Reviewed
