Repository fomantic/Fomantic-UI, pull requests merged in 2018-07, with the labels that each got.

#51 [Label] :ActiveHover is not a valid selector error #5908
  src/definitions/elements/label.less
Labels: CSS

#49 [Icon] Allow both rotated and flipped icons
  src/definitions/elements/icon.less
Labels: CSS, Needs Doc Changes

#48 [Tab] Last tab should still have a bottom margin
  src/definitions/elements/segment.less
Labels: CSS

#47 [Modal] In Chrome, Modals close on Mouse up outside the Modal
  src/definitions/modules/modal.js
Labels: JavaScript

#42 [Modal] Revert "Add solve for dimmer to prevent modal scrolling in bg"
  src/definitions/modules/dimmer.js
Labels: JavaScript

#41 [Search] Add setting for error header in search results (Fix #6442)
  src/definitions/modules/search.js
Labels: JavaScript, Needs Changes, Needs Reviewed

#43 [Dropdown] Add possibility to add header items during js initialization
  src/definitions/modules/dropdown.js
Labels: Enhancement, JavaScript, Needs Doc Changes

#44 [Dropdown] Clean select mutation code
  src/definitions/modules/dropdown.js
Labels: JavaScript

#50 [Modal] Fullscreen Modals since 2.3.0 regression in Safari
  src/definitions/modules/modal.less
Labels: CSS

#39 [Dropdown] Fix searchable dropdown that doesn't get focus on show
  src/definitions/modules/dropdown.js
Labels: JavaScript

#46 [Dropdown] Add clear icon in single selection mode
  src/definitions/modules/dropdown.js
  src/definitions/modules/dropdown.less
Labels: CSS, Docs Added, Enhancement, JavaScript

#58 Invalid inverted message
  src/themes/default/modules/dropdown.overrides
Labels: CSS, Confirmed Bug

#62 [Button] tertiary buttons have @basicDownBackground when :active
  src/themes/default/elements/button.variables
Labels: CSS, Confirmed Bug

#61 [Docs] build error on new node version
  tasks/docs/build.js
Labels: Build Tools

#67 Fix clearable dropdown margin
  src/definitions/modules/dropdown.less
Labels: CSS, Needs Reviewed

#69 Fix for bad positionned icon group in a menu item
  src/definitions/collections/menu.less
Labels: CSS, Needs Reviewed

#68 Fix for icon group inside button missing margin
  src/definitions/elements/button.less
Labels: CSS, Needs Reviewed

#70 Fix the dropdown pointer that still remains after dropdown menu is collapsed
  src/definitions/modules/dropdown.less
Labels: CSS, Needs Reviewed

#72 [Loader] Added loader speed variants
  src/definitions/elements/loader.less
  src/themes/default/globals/site.variables
Labels: CSS, Enhancement, Needs Doc Changes

#74 Fix incorrect top attached header top margin
  src/definitions/elements/header.less
Labels: CSS

#75 Fixed textarea having wrong font family
  src/definitions/collections/form.less
Labels: CSS, Needs Reviewed

#76 Disabled rating
  RELEASE-NOTES.md
  src/definitions/modules/rating.js
Labels: Docs Added, Enhancement, JavaScript
