Repository fomantic/Fomantic-UI, pull requests merged in 2018-12, with the labels that each got.

#272 [Dropdown] Clearable dropdown initialized with a select always showed remove icon
  src/definitions/modules/dropdown.js
  src/definitions/modules/dropdown.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:, lang: JavaScript :scroll:

#273 [Modal] Touch Scrolling (dropdown, content, focussed input) fixed
  src/definitions/modules/modal.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#277 [Input, Textarea] Support for corner label and icon in textarea
  src/definitions/elements/input.less
  src/themes/default/elements/input.variables
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:

#279 [Message] fixed compact icon message width
  src/definitions/collections/message.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#287 [Dropdown] Filter already selected items when using remote api as datastore
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#286 [Form, Dropdown] Formvalidation broke when id has colon in it
  src/definitions/behaviors/form.js
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, :wrench: refactor, lang: JavaScript :scroll:

#283 [Dropdown] Fixed Submenu positioning
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#285 [Dropdown] Preselected values are ignored when data has individual value-name
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#288 [Modal] Dimmer-Click closed Modal when allowMultiple=true even if onHide()=false
  src/definitions/modules/modal.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#282 [Global]: Remove deprecated jquery functions
  src/definitions/behaviors/api.js
  src/definitions/behaviors/form.js
  src/definitions/behaviors/state.js
  src/definitions/behaviors/visibility.js
  src/definitions/globals/site.js
  src/definitions/modules/accordion.js
  src/definitions/modules/calendar.js
  src/definitions/modules/checkbox.js
  src/definitions/modules/dimmer.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/embed.js
  src/definitions/modules/modal.js
  src/definitions/modules/nag.js
  src/definitions/modules/popup.js
  src/definitions/modules/progress.js
  src/definitions/modules/rating.js
  src/definitions/modules/search.js
  src/definitions/modules/shape.js
  src/definitions/modules/sidebar.js
  src/definitions/modules/sticky.js
  src/definitions/modules/tab.js
  src/definitions/modules/toast.js
  src/definitions/modules/transition.js
Labels: :eyes: needs reviewed, :wrench: refactor, lang: JavaScript :scroll:

#275 [CSS] Fix some errors
  src/definitions/collections/form.less
  src/definitions/collections/table.less
  src/definitions/elements/flag.less
  src/definitions/elements/icon.less
  src/definitions/elements/step.less
  src/definitions/modules/modal.less
  src/definitions/modules/popup.less
  src/themes/classic/elements/button.variables
  src/themes/default/elements/button.variables
  src/themes/default/elements/list.variables
  src/themes/default/modules/modal.variables
  src/themes/default/views/item.variables
  src/themes/default/views/statistic.variables
Labels: :bug: bugfix, :eyes: needs reviewed, lang: CSS :art:

#297 [Visibility] rename placeholder class
  src/definitions/behaviors/visibility.js
Labels: :bug: bugfix, lang: JavaScript :scroll:

#298 [Search,Dropdown,XSS] prevent JS execution from manual entries or untrusted remote data
  src/definitions/modules/dropdown.js
  src/definitions/modules/search.js
Labels: :lock: security, :sleeping: sui issue, :triangular_ruler: needs doc changes, lang: JavaScript :scroll:

#295 [Checkbox] Support onChange for cursor keynav
  src/definitions/modules/checkbox.js
Labels: :bug: bugfix, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#299 [DropDown] Filter Preselected entries from #287 was not working for div-dropdowns
  src/definitions/modules/dropdown.js
Labels: :bug: bugfix, :eyes: needs reviewed, lang: JavaScript :scroll:, priority: high :rotating_light:

#304 [Build] Trying to fix CI
  package-lock.json
Labels: :bug: bugfix, :electric_plug: build tools, :eyes: needs reviewed, :hammer: CI/CD

#310 [Modal] Fix top border radius when allowMultiple is true
  src/definitions/modules/modal.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#303 [Rating] Individual icons and colors instead of fixed star+heart only
  src/definitions/modules/rating.js
  src/definitions/modules/rating.less
  src/themes/default/modules/rating.overrides
  src/themes/default/modules/rating.variables
Labels: :eyes: needs reviewed, :sleeping: sui issue, :triangular_ruler: needs doc changes, :zap: enhancement, UI component, lang: CSS :art:, lang: JavaScript :scroll:

#300 [Dropdown] Show "no results" when filterRemoteData is false and response is empty
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#309 [Build] Building hangs on 'create install files'
  package-lock.json
  package.json
  tasks/install.js
Labels: :bug: confirmed bug, :electric_plug: build tools

#311 [README] Added package quality badge and jsdelivr rounded style (to match other badges)
  README.md
Labels: :page_facing_up: documents

#290 [Range] implement SUI slider changes and more
  src/definitions/globals/site.js
  src/definitions/modules/range.js
  src/definitions/modules/range.less
  src/definitions/modules/slider.js
  src/definitions/modules/slider.less
  src/semantic.less
  src/theme.config.example
  src/themes/default/modules/range.variables
  src/themes/default/modules/slider.overrides
  src/themes/default/modules/slider.variables
  tasks/config/admin/release.js
  tasks/config/defaults.js
  tasks/config/project/install.js
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, UI component, lang: CSS :art:, lang: JavaScript :scroll:

#301 [Loader] Centralised, Double+Elastic, other modules supported and dimmer option added
  src/definitions/collections/form.less
  src/definitions/elements/button.less
  src/definitions/elements/input.less
  src/definitions/elements/loader.less
  src/definitions/elements/segment.less
  src/definitions/modules/dimmer.js
  src/definitions/modules/dropdown.less
  src/definitions/modules/search.less
  src/definitions/modules/tab.less
  src/themes/default/elements/loader.variables
  src/themes/default/modules/tab.variables
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, UI component, lang: CSS :art:, lang: JavaScript :scroll:

#318 docs(issue template): remove old template
  .github/ISSUE_TEMPLATE.md
Labels: :page_facing_up: documents

#261 [Colors] Central dynamic color map for every component
  src/definitions/collections/grid.less
  src/definitions/collections/menu.less
  src/definitions/collections/message.less
  src/definitions/collections/table.less
  src/definitions/elements/button.less
  src/definitions/elements/header.less
  src/definitions/elements/icon.less
  src/definitions/elements/label.less
  src/definitions/elements/loader.less
  src/definitions/elements/segment.less
  src/definitions/elements/text.less
  src/definitions/modules/progress.less
  src/definitions/modules/rating.less
  src/definitions/modules/slider.less
  src/definitions/modules/toast.less
  src/definitions/views/card.less
  src/definitions/views/statistic.less
  src/semantic.less
  src/theme.config.example
  src/theme.less
  src/themes/default/elements/label.variables
  src/themes/default/elements/text.overrides
  src/themes/default/elements/text.variables
  src/themes/default/globals/colors.less
  src/themes/default/globals/site.variables
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, UI component, lang: CSS :art:

#321 2.7 hotfixes
  src/definitions/collections/menu.less
  src/definitions/elements/loader.less
Labels: :bug: bugfix, lang: CSS :art:

#325 [Dropdown, Input, Loader] Elastic Animation Style had wrong color
  src/definitions/elements/loader.less
Labels: :bug: bugfix, :eyes: needs reviewed, lang: CSS :art:

#334 [Button] Increased size specificity to work with menu item buttons
  src/definitions/elements/button.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#336 [List,Icon] List Item Icon Rotates Around Wrong Point when using Loading class
  src/definitions/elements/list.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#329 [Input] Support error class on input action buttons
  src/definitions/elements/input.less
Labels: :eyes: needs reviewed, :sleeping: sui issue, :zap: enhancement, lang: CSS :art:

#331 [Label] Remove hardcoded color exception "not()" for menu item labels
  src/definitions/collections/menu.less
  src/definitions/elements/label.less
Labels: :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:
