Repository fomantic/Fomantic-UI, pull requests merged in 2019-09, with the labels that each got.

#977 feat(tab): auto activate first tab if no active specified
  src/definitions/modules/tab.js
Labels: :zap: enhancement, lang: JavaScript :scroll:

#978 feat(slider): add auto adjusted label display
  src/definitions/modules/slider.js
  src/definitions/modules/slider.less
Labels: :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:, lang: JavaScript :scroll:

#981 fix(form): 'set values' behavior had no proper calendar support
  src/definitions/behaviors/form.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#994 fix(dropdown): setting value of dropdown did not remove search
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :sleeping: sui issue, lang: JavaScript :scroll:

#995 [Calendar] Fix broken dates when keyboard typed
  src/definitions/modules/calendar.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#1001 [List] use hex notation for unicode character
  src/themes/default/elements/list.variables
Labels: :sleeping: sui issue, lang: CSS :art:

#1004 fix(calendar): cross browser support for dateparsing using dots
  src/definitions/modules/calendar.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#1013 fix(modal): vertical alignment on detachable modal was incorrect
  src/definitions/modules/modal.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#1025 fix(tab): do not auto activate tabs more than once
  src/definitions/modules/tab.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:
