Repository fomantic/Fomantic-UI, pull requests merged in 2019-08, with the labels that each got.

#946 Move away from travis and to GitGub Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: :globe_with_meridians: platform, :hammer: CI/CD

#945 build: emit errors instead of logging only
  tasks/config/tasks.js
Labels: :electric_plug: build tools

#947 Fix CI and build errors
  .github/workflows/ci.yml
  tasks/config/tasks.js
Labels: :electric_plug: build tools, :hammer: CI/CD

#948 build(ci): fix ci process
  .github/workflows/ci.yml
  tasks/config/tasks.js
Labels: :electric_plug: build tools

#941 type'o fix in JS example
  src/README.md
Labels: :page_facing_up: documents

#912 fix(dropdown): sanitize initial values to prevent xss on firefox & ie
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :lock: security, browser: firefox, browser: ie, lang: JavaScript :scroll:

#957 feat(dropdown): add select optgroup and horizontal divider support
  src/definitions/modules/dropdown.js
  src/definitions/modules/dropdown.less
Labels: :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:, lang: JavaScript :scroll:

#955 [Dropdown] Keep input field focus if it's an menu item
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#954 fix(progress): wrong error on validating sum of rounded percents
  src/definitions/modules/progress.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#918 [Form] Check for existing calendar, dropdown or checkbox modules
  src/definitions/behaviors/form.js
Labels: :zap: enhancement, lang: JavaScript :scroll:

#926 fix(label): top attached labels omitted margin for content
  src/definitions/elements/label.less
Labels: :bug: confirmed bug, lang: CSS :art:

#979 feat(site): add font-display variable
  src/themes/default/globals/site.variables
Labels: :zap: enhancement, lang: CSS :art:
