Repository fomantic/Fomantic-UI, pull requests merged in 2019-10, with the labels that each got.

#1048 fix(grid): fix padding on stackable compact grid on mob devices
  src/definitions/collections/grid.less
Labels: :bug: confirmed bug, lang: CSS :art:

#1049 feat(table): add colored left & right row border
  src/definitions/collections/table.less
  src/themes/default/collections/table.variables
Labels: :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:

#1088 [Modal] Don't close modal when scrollbar is clicked in rtl enviroment
  src/definitions/modules/modal.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#1066 fix(calendar): prevent toggle range class at today button
  src/definitions/modules/calendar.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#1090 fix(modal): make bottom margin scrolling modals work in firefox & edge
  src/definitions/modules/modal.less
Labels: :bug: confirmed bug, lang: CSS :art:

#1096 fix(modal): correct undetached positioning when large modal is used
  src/definitions/modules/modal.js
  src/definitions/modules/modal.less
  src/themes/default/modules/modal.variables
Labels: :bug: confirmed bug, :sleeping: sui issue, lang: CSS :art:, lang: JavaScript :scroll:

#1101 feat(dropdown): add case sensitivity setting for search
  src/definitions/modules/dropdown.js
Labels: :triangular_ruler: needs doc changes, :zap: enhancement, lang: JavaScript :scroll:

#1100 fix(dropdown): use regular event handler for allowAdditions input blur
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#1095 fix(dropdown): prevent blur when hiding dropdown directly after search
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#1067 feat(form): accept 1 in addition to true as checked value for checkboxes
  src/definitions/behaviors/form.js
Labels: :zap: enhancement, lang: JavaScript :scroll:

#1092 fix(form): dont trigger change for dropdown when form is cleared
  src/definitions/behaviors/form.js
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :triangular_ruler: needs doc changes, lang: JavaScript :scroll:

#1083 fix(table): add td support in tfoot tag
  src/definitions/collections/table.less
Labels: :bug: confirmed bug, lang: CSS :art:

#1080 feat(progress): made setting to 100% optional when set error/warning
  src/definitions/modules/progress.js
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, lang: JavaScript :scroll:

#1078 chore(templates): add labels to new issue to reduce triage effort
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Help_wanted.md
Labels: :globe_with_meridians: platform

#1073 fix(dropdown): action button has incorrect border radius with dropdown
  src/definitions/elements/input.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#1068 fix(form): trigger correct dirty handlers to fix function of checkboxes
  src/definitions/behaviors/form.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#1062 fix(input): icon inputs have wrong padding when inside menus
  src/definitions/elements/input.less
Labels: :bug: confirmed bug, lang: CSS :art:

#1060 fix(dropdown): dont adjustment dropdown icon when inside a label button
  src/definitions/modules/dropdown.less
Labels: :bug: confirmed bug, lang: CSS :art:

#1008 fix(slider): add fireOnInit parameter to prevent events being triggered
  src/definitions/modules/slider.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#1102 build(actions): add nightly build action
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  package-lock.json
  package.json
  scripts/nightly-version.js
  scripts/preinstall.sh
Labels: :globe_with_meridians: platform, :hammer: CI/CD

#1082 [Slider] preventCrossover setting for range sliders
  src/definitions/modules/slider.js
Labels: :triangular_ruler: needs doc changes, :zap: enhancement, lang: JavaScript :scroll:, 🚨 breaking change
