Repository fomantic/Fomantic-UI, pull requests merged in 2019-02, with the labels that each got.

#446 [Icons] update icons to FontAwesome 5.7
  src/themes/default/assets/fonts/brand-icons.eot
  src/themes/default/assets/fonts/brand-icons.svg
  src/themes/default/assets/fonts/brand-icons.ttf
  src/themes/default/assets/fonts/brand-icons.woff
  src/themes/default/assets/fonts/brand-icons.woff2
  src/themes/default/assets/fonts/icons.eot
  src/themes/default/assets/fonts/icons.svg
  src/themes/default/assets/fonts/icons.ttf
  src/themes/default/assets/fonts/icons.woff
  src/themes/default/assets/fonts/icons.woff2
  src/themes/default/assets/fonts/outline-icons.eot
  src/themes/default/assets/fonts/outline-icons.svg
  src/themes/default/assets/fonts/outline-icons.ttf
  src/themes/default/assets/fonts/outline-icons.woff
  src/themes/default/assets/fonts/outline-icons.woff2
  src/themes/default/elements/icon.overrides
Labels: :bookmark_tabs: docs added, :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:

#450 docs(roadmap): add roadmap
  ROADMAP.md
Labels: :page_facing_up: documents

#451 docs(readme): add v3 development message
  README.md
Labels: :page_facing_up: documents

#457 [Card] Bottom attached colored buttons left blurry grey bottom line
  src/definitions/views/card.less
Labels: :bug: bugfix, lang: CSS :art:

#463 [Progress] Fix 0 percent bars on colored progress
  src/definitions/modules/progress.less
Labels: :bug: bugfix, :eyes: needs reviewed, lang: CSS :art:

#472 fix(build): write metadata.json for docs
  tasks/docs/build.js
Labels: :electric_plug: build tools

#474 [Transition] Transitions made of hidden inline style elements were not animated correctly anymore
  src/definitions/modules/transition.js
Labels: :bug: bugfix, :eyes: needs reviewed, lang: JavaScript :scroll:

#465 [Shape] Transition did not work when child element also had a transition set
  src/definitions/modules/shape.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#455 [Card] Support inverted colors
  src/definitions/views/card.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#469 [Sidebar] Make closable only work in clickaway event as stated in the docs
  src/definitions/modules/sidebar.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#470 [Segment] Fix support for inverted, secondary or tertiary in horizontal segments
  src/definitions/elements/segment.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#501 [Build] Refactor dependencies
  .travis.yml
  package-lock.json
  package.json
Labels: :electric_plug: build tools

#485 [Segment] Make Clearing segment work with stacked or piled segments
  src/definitions/elements/segment.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#487 [Button] Basic colored buttons were overridden by basic button group box shadow
  src/definitions/elements/button.less
Labels: :bug: bugfix, :eyes: needs reviewed, lang: CSS :art:

#488 [Segment,Header] Color sub header in inverted segment just like normal header
  src/definitions/elements/segment.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#490 [Menu] Disabled items in tabular menus had same color as normal items
  src/definitions/collections/menu.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#491 [Checkbox] Visual support for indeterminate toggle
  src/definitions/modules/checkbox.less
  src/themes/default/modules/checkbox.variables
Labels: :eyes: needs reviewed, :sleeping: sui issue, :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:

#492 [Input] Tiny size variant was missing
  src/definitions/elements/input.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#497 [API] Do not raise console error on all 2xx status codes on failure
  src/definitions/behaviors/api.js
Labels: :eyes: needs reviewed, :sleeping: sui issue, :zap: enhancement, lang: JavaScript :scroll:

#481 [Popup] onHide was called twice
  src/definitions/modules/popup.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#482 [Label] Table ribbon labels had wrong calculated position
  src/themes/default/elements/label.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#483 [Progress] Inverted success/warning/error progress bars had no color
  src/definitions/modules/progress.less
Labels: :bug: bugfix, :eyes: needs reviewed, lang: CSS :art:

#480 [Menu] Last right item in a menu inside a container misses right border
  src/definitions/collections/menu.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#479 [Segment] compact segment in horizontal segment group should stay compact
  src/definitions/elements/segment.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#478 [Dropdown] Allow a label to be clickable inside a dropdown button
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#510 [Dropdown] Always show list when clicked on icon, regardless of minCharacter setting
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#512 [Modal] A modal couldnt be closed a second time it was opened by another modal
  src/definitions/modules/modal.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#513 [Calendar] Day was calculated to last day of month if year had 2-digit notation between 60 and 99
  src/definitions/modules/calendar.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#506 [Dropdown] Catch a possible null value for preselected values
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#509 [Checkbox] Support check/uncheck by hitting space key in IE11 and Edge
  src/definitions/modules/checkbox.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, browser: edge, browser: ie, device: desktop/laptop, lang: JavaScript :scroll:

#499 [Tab] should escape meta characters before sending to jquery
  src/definitions/modules/tab.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#464 [Shape] Fix 3D flip starting zoom, fix nested shapes, ignore child elements with class 'active'
  src/definitions/modules/shape.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#468 [Modal] Don't move content and modal on dimmer when scrollbar hides
  src/definitions/modules/dimmer.js
  src/definitions/modules/modal.js
  src/definitions/modules/sidebar.less
Labels: :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:, lang: JavaScript :scroll:

#520 [Label] Make corner icon position absolute to support other tags for label like <button>
  src/definitions/elements/label.less
  src/themes/default/elements/label.variables
Labels: :zap: enhancement, lang: CSS :art:

#525 [Calendar] Disable all dates but some
  src/definitions/modules/calendar.js
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, lang: JavaScript :scroll:

#526 [Modal] Introducing "overlay fullscreen modal"
  src/definitions/modules/modal.less
  src/themes/default/modules/modal.variables
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:

#527 [Calendar] Adjustable shortyear to century calculation
  src/definitions/modules/calendar.js
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, lang: JavaScript :scroll:
