Repository fomantic/Fomantic-UI, pull requests merged in 2019-06, with the labels that each got.

#794 fix(table): table header on mobile
  src/definitions/collections/table.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, device: mobile :iphone:, lang: CSS :art:

#785 fix(dropdown): check for existing observer before accessing it
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#761 build(composer): fix typo, add web property & changed domain to FUI
  composer.json
  tasks/config/admin/templates/composer.json
Labels: :electric_plug: build tools, :eyes: needs reviewed, :sleeping: sui issue, 🐛 bugfix

#760 fix(form): remove rule function lead to TypeError
  src/definitions/behaviors/form.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#772 [Button] Center button text in fluid & vertically aligned button group
  src/definitions/elements/button.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#801 fix(form): transparent input padding and texarea support
  src/definitions/collections/form.less
  src/definitions/elements/input.less
  src/themes/default/elements/input.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#776 build(theme.less): adjust line numbers for error messages
  tasks/config/tasks.js
Labels: :electric_plug: build tools, :eyes: needs reviewed, 🐛 bugfix

#773 docs(security): add security policy
  SECURITY.md
Labels: :eyes: needs reviewed, :globe_with_meridians: platform, :page_facing_up: documents

#767 fix(form): stop propagation only when dirty event was triggered and prevent default action
  src/definitions/behaviors/form.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#762 refactor(*): clean up deprecated symbols
  src/definitions/behaviors/api.js
  src/definitions/modules/calendar.js
  src/definitions/modules/embed.js
  src/definitions/modules/embed.less
  src/definitions/modules/popup.js
Labels: :eyes: needs reviewed, :zap: enhancement, lang: JavaScript :scroll:

#758 [Progress] Fix wrong error on validating sum total on multiple progress
  src/definitions/modules/progress.js
Labels: :bug: confirmed bug, :triangular_ruler: needs doc changes, lang: JavaScript :scroll:

#752 fix(calendar): support dynamic way to append popup instead of prepending to the parent
  src/definitions/modules/calendar.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#737 fix(button,table): move LESS functions out of LESS file and into variables
  src/definitions/collections/table.less
  src/definitions/elements/button.less
  src/themes/default/globals/colors.less
  src/themes/default/globals/site.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#735 feat(progress): add indeterminate states
  src/definitions/modules/progress.less
  src/themes/default/modules/progress.variables
Labels: :bookmark_tabs: docs added, :eyes: needs reviewed, :sleeping: sui issue, :zap: enhancement, lang: CSS :art:

#803 fix(menu): hover & active state colors on inverted secondary pointing
  src/definitions/collections/menu.less
  src/themes/default/collections/menu.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#810 build(autoprefixer): change 'browsers' setting to 'overrideBrowserslist'
  tasks/config/tasks.js
Labels: :electric_plug: build tools, :eyes: needs reviewed, :zap: enhancement

#826 docs(contributing): fix repository typo
  CONTRIBUTING.md
Labels: :page_facing_up: documents

#832 feat(modal): destroy should tear down mutation observer
  src/definitions/modules/modal.js
Labels: :eyes: needs reviewed, :zap: enhancement, lang: JavaScript :scroll:

#824 feat(checkbox): add toggle on ENTER-key option
  src/definitions/modules/checkbox.js
Labels: :bookmark_tabs: docs added, :eyes: needs reviewed, :zap: enhancement, lang: JavaScript :scroll:

#831 fix(step): step visualization also on non active
  src/definitions/elements/step.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:
