Repository fomantic/Fomantic-UI, pull requests merged in 2019-05, with the labels that each got.

#709 fix(form validation): error when calling "validate form" with API attached
  src/definitions/behaviors/form.js
Labels: :bug: confirmed bug, :sleeping: sui issue, lang: JavaScript :scroll:

#714 fix(list): align text in lists with icons
  src/definitions/elements/list.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#715 fix(label): adjust basic ribbon label size and position
  src/definitions/elements/label.less
  src/themes/default/elements/label.variables
Labels: :bug: confirmed bug, lang: CSS :art:

#721 fix(breadcrumb): increase line height for readability on wrapped content
  src/definitions/collections/breadcrumb.less
Labels: :sleeping: sui issue, :zap: enhancement, lang: CSS :art:

#720 feat(breadcrumb): add inverted variant
  src/definitions/collections/breadcrumb.less
  src/themes/default/collections/breadcrumb.variables
Labels: :eyes: needs reviewed, :sleeping: sui issue, :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:

#718 feat(dropdown): add scrolling support for simple variant
  src/definitions/modules/dropdown.less
Labels: :sleeping: sui issue, :zap: enhancement, lang: CSS :art:

#703 fix(card): word-wrap overflowing with long strings
  src/definitions/views/card.less
Labels: :bug: confirmed bug, :sleeping: sui issue, lang: CSS :art:

#706 [Progess] Fix timing issue of updating value/percent
  src/definitions/modules/progress.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#711 fix(progess): all percents are shown while animation
  src/definitions/modules/progress.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#712 fix(search): undefined internal variable
  src/definitions/modules/search.js
Labels: :bug: confirmed bug, :sleeping: sui issue, lang: JavaScript :scroll:

#722 fix(api): module callback function typo
  src/definitions/behaviors/api.js
Labels: :sleeping: sui issue, lang: JavaScript :scroll:, 🐛 bugfix

#725 fixed submitting
  README.md
Labels: :page_facing_up: documents

#669 [Menu] Leave floating labels in secondary pointing menus as they are
  src/definitions/collections/menu.less
Labels: :bug: confirmed bug, lang: CSS :art:

#731 fix(menu): correct submenu fix which broke right menus
  src/definitions/collections/menu.less
Labels: :bug: confirmed bug, lang: CSS :art:

#733 build(deps): update jquery
  bower.json
  package-lock.json
  package.json
Labels: :electric_plug: build tools, :eyes: needs reviewed, :lock: security

#730 feat(icons): update to FA 5.8.2
  src/themes/default/assets/fonts/brand-icons.eot
  src/themes/default/assets/fonts/brand-icons.svg
  src/themes/default/assets/fonts/brand-icons.ttf
  src/themes/default/assets/fonts/brand-icons.woff
  src/themes/default/assets/fonts/brand-icons.woff2
  src/themes/default/assets/fonts/icons.eot
  src/themes/default/assets/fonts/icons.svg
  src/themes/default/assets/fonts/icons.ttf
  src/themes/default/assets/fonts/icons.woff
  src/themes/default/assets/fonts/icons.woff2
  src/themes/default/assets/fonts/outline-icons.eot
  src/themes/default/assets/fonts/outline-icons.svg
  src/themes/default/assets/fonts/outline-icons.ttf
  src/themes/default/assets/fonts/outline-icons.woff
  src/themes/default/assets/fonts/outline-icons.woff2
  src/themes/default/elements/icon.overrides
  src/themes/default/elements/icon.variables
Labels: :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:

#748 fix(transition): not checking for event object lead to TypeError
  src/definitions/modules/transition.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#743 fix(calendar): support JSON dates
  src/definitions/modules/calendar.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#751 fix(slider): non reachable max value and rounding issues
  src/definitions/modules/slider.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#750 docs(roadmap): update with more detail
  ROADMAP.md
Labels: :globe_with_meridians: platform, :page_facing_up: documents

#764 fix(icon): don't import default theme overrides
  src/definitions/elements/icon.less
  src/theme.less
Labels: lang: CSS :art:, 🐛 bugfix

#765 fix(icon): improve default theme overrides import
  src/definitions/elements/icon.less
  src/theme.less
Labels: lang: CSS :art:, 🐛 bugfix
