Repository fomantic/Fomantic-UI, pull requests merged in 2019-12, with the labels that each got.

#1201 docs(readme): add snyk badge
  README.md
Labels: :page_facing_up: documents

#1198 fix(table): dont show background on sortable headers if table is basic
  src/definitions/collections/table.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#1208 fix(form): avoid additional margin with nested fields
  src/definitions/collections/form.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#1197 fix(form): action input had wrong border radius in some cases
  src/definitions/collections/form.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#1220 fix(dropdown): clearable icon is not clickable on mobile
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#1228 [Form] `add rule` was overwriting existing rules
  src/definitions/behaviors/form.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#1222 fix(chore): duplicate variable declaration
  src/themes/default/globals/variation.variables
Labels: :zap: enhancement, lang: CSS :art:

#1216 feat(popup): add variant to ensure width if parent container is to small
  src/definitions/modules/popup.less
  src/themes/default/globals/variation.variables
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:

#1215 feat(modal): allow close icon to be inside header for small modals
  src/definitions/modules/modal.less
  src/themes/default/globals/variation.variables
Labels: :eyes: needs reviewed, :sleeping: sui issue, :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:

#1217 fix(popup): tooltips don't work on safari <= 12.1
  src/definitions/modules/popup.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, browser: safari, lang: CSS :art:

#1229 feat(dropdown): add unfilterable item class for search input
  src/definitions/modules/dropdown.js
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, lang: JavaScript :scroll:

#1232 fix(slider): preventCrossover should only affect range sliders
  src/definitions/modules/slider.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#1227 build(actions): stop nightly error on forks
  .github/workflows/nightly.yml
Labels: :hammer: CI/CD

#1223 fix(dimmer): borders on partial segment dimmers are incorrect
  src/definitions/modules/dimmer.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#1219 fix(dropdown): handle text metadata on select build dropdowns
  src/definitions/modules/dropdown.js
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, lang: JavaScript :scroll:

#1210 fix(dropdown): values are incorrect if they contain some special chars
  src/definitions/modules/dropdown.js
  src/definitions/modules/popup.js
  src/definitions/modules/search.js
  src/definitions/modules/toast.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#1209 fix(dropdown): do not use value as name when name is empty
  src/definitions/modules/dropdown.js
  src/definitions/modules/dropdown.less
  src/themes/default/modules/dropdown.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:
