Repository fomantic/Fomantic-UI, pull requests merged in 2019-11, with the labels that each got.

#1143 fix(slider): offset for reversed vertical slider
  src/definitions/modules/slider.less
  src/themes/default/modules/slider.variables
Labels: :bug: confirmed bug, lang: CSS :art:

#1135 fix(dropdown): parameter count resulted in wrong data for onchange
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:, 🚨 breaking change

#1098 feat(form): generalize state variations for field
  src/definitions/collections/form.less
  src/definitions/elements/input.less
  src/definitions/modules/dropdown.less
  src/themes/default/collections/form.variables
  src/themes/default/elements/input.variables
  src/themes/default/globals/colors.less
  src/themes/default/globals/site.variables
  src/themes/default/modules/dropdown.variables
Labels: :bookmark_tabs: docs added, :zap: enhancement, lang: CSS :art:

#1002 fix(dropdown): remove searchterm if nothing matches & opts are disabled
  src/definitions/modules/dropdown.js
Labels: :zap: enhancement, lang: JavaScript :scroll:, 🚨 breaking change

#1052 feat(dropdown): optional skip focus when calling 'show' behavior
  src/definitions/modules/dropdown.js
Labels: :bookmark_tabs: docs added, :zap: enhancement, lang: JavaScript :scroll:

#982 feat(calendar): add onBeforeChange callback and fix a date value issue
  src/definitions/modules/calendar.js
Labels: :bookmark_tabs: docs added, :eyes: needs reviewed, lang: JavaScript :scroll:, 🚨 breaking change

#1111 fix(popup): avoid detection of wrong existing popup
  src/definitions/modules/popup.js
Labels: :bug: confirmed bug, :sleeping: sui issue, lang: JavaScript :scroll:

#1033 build(theme): allow null for @site
  src/theme.less
Labels: :electric_plug: build tools, :zap: enhancement, lang: CSS :art:

#1156 [Task] Make sure permission value is tranformed into correct octal value for gulp chmod
  tasks/config/defaults.js
Labels: :bug: confirmed bug, :electric_plug: build tools

#1149 [Slider] Fix touch events handling when jquery 2 is used
  src/definitions/modules/slider.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#1144 [Card] Right images in horizontal cards had wrong border radius
  src/definitions/views/card.less
Labels: :bug: confirmed bug, lang: CSS :art:

#1145 [Card] Horizontal cards on mobile got cut
  src/themes/default/views/card.variables
Labels: :bug: confirmed bug, lang: CSS :art:

#1151 [Slider] Hidden sliders render in an endless while loop freezing the browser
  src/definitions/modules/slider.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#1148 feat(icons): update icons to FA 5.11.2
  src/themes/default/assets/fonts/brand-icons.eot
  src/themes/default/assets/fonts/brand-icons.svg
  src/themes/default/assets/fonts/brand-icons.ttf
  src/themes/default/assets/fonts/brand-icons.woff
  src/themes/default/assets/fonts/brand-icons.woff2
  src/themes/default/assets/fonts/icons.eot
  src/themes/default/assets/fonts/icons.svg
  src/themes/default/assets/fonts/icons.ttf
  src/themes/default/assets/fonts/icons.woff
  src/themes/default/assets/fonts/icons.woff2
  src/themes/default/assets/fonts/outline-icons.eot
  src/themes/default/assets/fonts/outline-icons.svg
  src/themes/default/assets/fonts/outline-icons.ttf
  src/themes/default/assets/fonts/outline-icons.woff
  src/themes/default/assets/fonts/outline-icons.woff2
  src/themes/default/elements/icon.overrides
Labels: :zap: enhancement, lang: CSS :art:

#1104 [Modal] Dont move modal content when rtl is enabled and scrollbar is to the left
  src/definitions/modules/modal.js
  src/definitions/modules/popup.js
  src/definitions/modules/sidebar.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#1056 fix close modal incorrect behaviour
  src/definitions/modules/modal.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#1051 [Table] Marked color feature also for individual cells
  src/definitions/collections/table.less
  src/themes/default/collections/table.variables
Labels: :bookmark_tabs: docs added, :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:

#1112 fix(dropdown): value on dynamically loaded select based dropdowns
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#1028 [Calendar] Don't limit word length for month parsing to support all languages
  src/definitions/modules/calendar.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:, 🚨 breaking change

#920 [Dropdown] Existing 'required' attribut for <select> prevents form submission
  src/definitions/modules/dropdown.js
Labels: :zap: enhancement, lang: JavaScript :scroll:, 🚨 breaking change

#1029 [Dropdown] Fix multiselect removing when ignoreCase is true
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#642 [API] Set context in beforesend to $module instead of possible stateContext to match docs
  src/definitions/behaviors/api.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:, 🚨 breaking change

#1011 [Container] increased specificity to correctly override grid container
  src/definitions/elements/container.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#1050 [Build] Variables in @site.variables are ignored
  src/theme.less
  tasks/build/css.js
Labels: :bug: confirmed bug, :electric_plug: build tools, :eyes: needs reviewed

#1074 [Rating] Render partial/non-integer ratings
  src/definitions/modules/rating.js
  src/definitions/modules/rating.less
Labels: :bookmark_tabs: docs added, :zap: enhancement, lang: CSS :art:, lang: JavaScript :scroll:

#1027 Update dimmer.less
  src/definitions/modules/dimmer.less
Labels: :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:

#1129 feat(toast): add actions, behaviors and other variations
  src/definitions/modules/toast.js
  src/definitions/modules/toast.less
  src/themes/default/modules/toast.variables
Labels: :bookmark_tabs: docs added, UI component, lang: CSS :art:, lang: JavaScript :scroll:, 🚨 breaking change

#326 feat(emoji): add emoji component using tweemoji & joypixels
  src/definitions/elements/emoji.less
  src/semantic.less
  src/theme.config.example
  src/themes/default/elements/emoji.overrides
  src/themes/default/elements/emoji.variables
  src/themes/joypixels/elements/emoji.overrides
  src/themes/joypixels/elements/emoji.variables
  src/themes/twitter/elements/emoji.overrides
  src/themes/twitter/elements/emoji.variables
  tasks/config/admin/release.js
  tasks/config/defaults.js
  tasks/config/project/install.js
Labels: :bookmark_tabs: docs added, UI component, lang: CSS :art:, 🚨 breaking change

#1157 feat(docs): Add lubber-de github account to funding info 😄
  .github/FUNDING.yml
Labels: :page_facing_up: documents

#781 feat(*): add dynamic LESS compilation of component variations
  src/definitions/collections/breadcrumb.less
  src/definitions/collections/form.less
  src/definitions/collections/grid.less
  src/definitions/collections/menu.less
  src/definitions/collections/message.less
  src/definitions/collections/table.less
  src/definitions/elements/button.less
  src/definitions/elements/container.less
  src/definitions/elements/divider.less
  src/definitions/elements/header.less
  src/definitions/elements/icon.less
  src/definitions/elements/image.less
  src/definitions/elements/input.less
  src/definitions/elements/label.less
  src/definitions/elements/list.less
  src/definitions/elements/loader.less
  src/definitions/elements/placeholder.less
  src/definitions/elements/rail.less
  src/definitions/elements/reveal.less
  src/definitions/elements/segment.less
  src/definitions/elements/step.less
  src/definitions/elements/text.less
  src/definitions/modules/accordion.less
  src/definitions/modules/calendar.less
  src/definitions/modules/checkbox.less
  src/definitions/modules/dimmer.less
  src/definitions/modules/dropdown.less
  src/definitions/modules/embed.less
  src/definitions/modules/modal.less
  src/definitions/modules/popup.less
  src/definitions/modules/progress.less
  src/definitions/modules/rating.less
  src/definitions/modules/search.less
  src/definitions/modules/shape.less
  src/definitions/modules/sidebar.less
  src/definitions/modules/slider.less
  src/definitions/modules/tab.less
  src/definitions/modules/toast.less
  src/definitions/modules/transition.less
  src/definitions/views/ad.less
  src/definitions/views/card.less
  src/definitions/views/comment.less
  src/definitions/views/feed.less
  src/definitions/views/item.less
  src/definitions/views/statistic.less
  src/themes/default/collections/message.variables
  src/themes/default/elements/header.variables
  src/themes/default/elements/input.variables
  src/themes/default/elements/list.variables
  src/themes/default/globals/site.variables
  src/themes/default/globals/variation.variables
  src/themes/default/modules/checkbox.variables
  src/themes/default/modules/modal.variables
  src/themes/default/modules/progress.variables
  src/themes/default/modules/search.variables
  src/themes/default/modules/slider.variables
  src/themes/default/views/item.variables
  src/themes/default/views/statistic.variables
Labels: :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:, 🚨 breaking change

#1161 fix(emoji): change emoji path to use svg
  src/themes/default/elements/emoji.variables
Labels: :bug: confirmed bug, lang: CSS :art:

#1174 build(actions): correct nightly build version
  scripts/nightly-version.js
Labels: :bug: confirmed bug, :hammer: CI/CD

#1175 fix(emoji): make emoji inherit font-size so they don't get cropped
  src/definitions/elements/emoji.less
  src/themes/default/elements/emoji.overrides
  src/themes/default/elements/emoji.variables
  src/themes/default/globals/variation.variables
  src/themes/joypixels/elements/emoji.overrides
  src/themes/joypixels/elements/emoji.variables
  src/themes/twitter/elements/emoji.overrides
  src/themes/twitter/elements/emoji.variables
Labels: :bookmark_tabs: docs added, :bug: confirmed bug, lang: CSS :art:

#1182 fix(input): action input border color in state fields
  src/definitions/elements/input.less
Labels: :bug: confirmed bug, lang: CSS :art:

#1189 [Checkbox] Fix npe on IE11
  src/definitions/modules/checkbox.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:
