Repository fomantic/Fomantic-UI, pull requests merged in 2019-03, with the labels that each got.

#529 [Shape] Focussed Checkbox inside shape breaks animation
  src/definitions/modules/shape.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#532 [Modal] Allow different modal positions on multi-modals. Added top and bottom aligned modal
  src/definitions/modules/modal.js
  src/definitions/modules/modal.less
  src/themes/default/modules/modal.variables
Labels: :bookmark_tabs: docs added, :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:, lang: JavaScript :scroll:

#534 [Dropdown] Missing event property in focus event raises JS error in firefox
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, browser: firefox, lang: JavaScript :scroll:

#537 [Button] Basic button loop always used "primary" for margin
  src/definitions/elements/button.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#538 [Refactoring] Remove unused local variables
  src/definitions/behaviors/form.js
  src/definitions/behaviors/state.js
  src/definitions/behaviors/visibility.js
  src/definitions/globals/site.js
  src/definitions/modules/accordion.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/embed.js
  src/definitions/modules/nag.js
  src/definitions/modules/rating.js
  src/definitions/modules/search.js
  src/definitions/modules/shape.js
  src/definitions/modules/sticky.js
  src/definitions/modules/transition.js
Labels: :wrench: refactor, lang: JavaScript :scroll:

#540 [Formvalidation] Support checkbox groups for "checked" rule like radio groups
  src/definitions/behaviors/form.js
Labels: :bug: bugfix, :eyes: needs reviewed, lang: JavaScript :scroll:

#544 [Checkbox] Proper check for non existent event object in Firefox
  src/definitions/modules/checkbox.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, browser: firefox, lang: JavaScript :scroll:

#560 Enhancements: [Dropdown] expose week cell class setting.
  src/definitions/modules/calendar.js
Labels: :triangular_ruler: needs doc changes, :zap: enhancement, lang: JavaScript :scroll:

#559 [Calendar] initialDate now update input
  src/definitions/modules/calendar.js
Labels: :bug: bugfix, lang: JavaScript :scroll:

#558 [Formvalidation] Safari was not showing error message
  src/definitions/collections/form.less
Labels: :bug: confirmed bug, :sleeping: sui issue, lang: CSS :art:

#556 [Form] behavior "remove rules" fail if field is Array
  src/definitions/behaviors/form.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#553 [Slider] Don't conflict with checkbox
  src/definitions/modules/slider.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#546 [Form validation] Check if `validation[field] !== undefined` before accessing any of it's properties
  src/definitions/behaviors/form.js
Labels: :bug: bugfix, :eyes: needs reviewed, lang: JavaScript :scroll:

#563 [Site] Remove unknown CSS property: font-smoothing
  src/definitions/globals/site.less
  src/themes/default/globals/site.variables
  src/themes/flat/globals/site.variables
Labels: :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:

#567 [Site] Support dpi > 100% for media queries
  src/themes/default/globals/site.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#571 [Dimmer] Loader inside simple inverted dimmer was still visible even when parent was not dimmed
  src/definitions/modules/dimmer.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#562 Enhancements: [Dropdown] Possibility to select adjacent month dates.
  src/definitions/modules/calendar.js
  src/definitions/modules/calendar.less
  src/themes/default/modules/calendar.variables
Labels: :bookmark_tabs: docs added, :zap: enhancement, lang: CSS :art:, lang: JavaScript :scroll:

#586 [Dropdown] Columnar dropdown variation
  src/definitions/modules/dropdown.less
Labels: :bookmark_tabs: docs added, :zap: enhancement, lang: CSS :art:

#584 [Button] Fixed padding for fluid right/left labeled icon buttons
  src/definitions/elements/button.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#583 [Step] Show step pointer and border also on stacked mobile for consistent look
  src/definitions/elements/step.less
Labels: :sleeping: sui issue, :zap: enhancement, lang: CSS :art:

#585 [Chore] Update jquery dependency for bower to the same version as for npm
  bower.json
Labels: :electric_plug: build tools, :sleeping: sui issue

#579 [Table] Inverted Table fixes for sortable header and disabled colored rows/cells
  src/definitions/collections/table.less
  src/themes/default/collections/table.variables
Labels: :bug: bugfix, :sleeping: sui issue, lang: CSS :art:

#582 [Progress] Allow multiple bars
  src/definitions/modules/progress.js
  src/definitions/modules/progress.less
Labels: :bookmark_tabs: docs added, :zap: enhancement, UI component, lang: CSS :art:, lang: JavaScript :scroll:

#587 [Dropdown] Height variation
  src/definitions/modules/dropdown.less
Labels: :bookmark_tabs: docs added, :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:
