Repository fomantic/Fomantic-UI, pull requests merged in 2019-07, with the labels that each got.

#838 fix(dropdown): correct clear icon alignment
  src/definitions/modules/dropdown.less
Labels: :bug: confirmed bug, lang: CSS :art:

#820 fix(form): inline field label doesn't respect error styles
  src/definitions/collections/form.less
Labels: :bug: confirmed bug, lang: CSS :art:

#860 Tell RTLCSS to ignore flag icon background-positions. Fix #859
  src/themes/default/elements/flag.overrides
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#864 docs(faq): update info
  FAQ.md
  faq.md
Labels: :eyes: needs reviewed, :page_facing_up: documents

#825 label + .ui.checkbox
  src/definitions/collections/form.less
  src/themes/default/collections/form.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#814 [Image] Hidden images were still visible when used in image groups
  src/definitions/elements/image.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#866 fix(form): prompt template function
  src/definitions/behaviors/form.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#797 Removing traling white spaces
  src/definitions/modules/modal.js
Labels: :eyes: needs reviewed, :wrench: refactor

#877 [CI] Verify build on pull requests
  .travis.yml
Labels: :eyes: needs reviewed, :hammer: CI/CD, :zap: enhancement

#875 [Dropdown] Support icon and or image settings as json properties
  src/definitions/modules/dropdown.js
  src/definitions/modules/dropdown.less
  src/themes/default/modules/dropdown.variables
Labels: :bookmark_tabs: docs added, :zap: enhancement, lang: CSS :art:, lang: JavaScript :scroll:

#899 [Dropdown] Don't toggle on "set selected" when no labels are used
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#863 Add all-contributors support
  .all-contributorsrc
  CONTRIBUTING.md
  CONTRIBUTORS.md
  README.md
  package-lock.json
  package.json
Labels: :eyes: needs reviewed, :globe_with_meridians: platform, :page_facing_up: documents

#895 [Search] Behavior 'get result:' Support numerical fields and make use of user defined searchFields
  src/definitions/modules/search.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#880 [Popup] Optional setting "forcePosition" to disable calculation, even if popup will not fit
  src/definitions/modules/popup.js
Labels: :bookmark_tabs: docs added, :eyes: needs reviewed, :zap: enhancement, lang: JavaScript :scroll:

#884 [Table] Colored definition table shows overlapping border in top left cell
  src/definitions/collections/table.less
  src/themes/default/collections/table.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#886 [Checkbox] Support sizes and form size inheritance
  src/definitions/modules/checkbox.less
  src/themes/default/globals/site.variables
  src/themes/default/modules/checkbox.variables
Labels: :eyes: needs reviewed, :sleeping: sui issue, :zap: enhancement, lang: CSS :art:

#889 [Dropdown] Corrected initial clearable icon when <select> was used for conversion
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#891 [Dropdown] Only preventdefault on hide for associating labels
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#894 [Accordion] Remove transition class after animation to make conten loader work again
  src/definitions/modules/accordion.js
Labels: :bug: confirmed bug, :sleeping: sui issue, lang: CSS :art:, lang: JavaScript :scroll:

#800 Fix content margin after two attached labels
  src/definitions/elements/label.less
Labels: :bug: confirmed bug, lang: CSS :art:

#903 [Container] Respect fluid container on mobile screen and remove !important
  src/definitions/elements/container.less
Labels: :bug: confirmed bug, :zap: enhancement, lang: CSS :art:
