Repository fomantic/Fomantic-UI, pull requests merged in 2019-04, with the labels that each got.

#608 build(deps): fix install issue caused by dev deps
  package-lock.json
  package.json
Labels: :bug: bugfix, :electric_plug: build tools, priority: high :rotating_light:

#612 [Dropdown] inverted pointing menu had white arrow (also moved code from overrides to less file)
  src/definitions/modules/dropdown.less
  src/themes/default/modules/dropdown.overrides
  src/themes/default/modules/dropdown.variables
Labels: :bug: bugfix, lang: CSS :art:

#605 [Modal] Don't close dimmer when another modal is still animating
  src/definitions/modules/modal.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#610 [Calendar] Support Date-Object given for parser.date, initialDate setting is wrongly displayed otherwise
  src/definitions/modules/calendar.js
Labels: :bug: bugfix, :eyes: needs reviewed, lang: JavaScript :scroll:

#593 [Dropdown] click-event was locked when single selection had allowAdditions enabled
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#594 [Dropdown] prevent submenu vanishing for simple dropdowns
  src/definitions/modules/dropdown.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#600 [Modal] Don't wrap image content direct images
  src/definitions/modules/modal.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#601 [Button] Fix padding for compact labeled icon button icon
  src/definitions/elements/button.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#602 [Table] Definition table footer had wrong box-shadow to the left
  src/definitions/collections/table.less
Labels: :bug: bugfix, :eyes: needs reviewed, lang: CSS :art:

#604 [Table] Don't break style when nested tables like calendar are used (or having different variants)
  src/definitions/collections/table.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#611 [Table] selectable rows/cells should have pointing cursor
  src/definitions/collections/table.less
Labels: :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:

#498 [API] Set context in beforesend to $module instead of possible stateContext to match docs
  src/definitions/behaviors/api.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :hand: on hold, :sleeping: sui issue, lang: JavaScript :scroll:

#616 [Dimmer] Don't blur a popup , might be used inside the dimmer like modal
  src/definitions/modules/dimmer.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#626 [Chore] Moved some core css from default overrides to less files and always include default overrides first
  src/definitions/collections/menu.less
  src/definitions/modules/rating.less
  src/theme.less
  src/themes/default/collections/menu.overrides
  src/themes/default/modules/rating.overrides
Labels: :bug: bugfix, :electric_plug: build tools, :eyes: needs reviewed

#632 [Menu]: Fixes right dropdown sub-menu not being vertical
  src/definitions/collections/menu.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#629 [Form] Adds segment corner rounding to form segments loader
  src/definitions/collections/form.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#627 [Popup] support iOS to recognize popup close on touch
  src/definitions/modules/popup.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#625 [Progress] Display 0-width bar when value is 0
  src/definitions/modules/progress.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#622 [Dropdown]: image and remove icons used as item icons are misaligned
  src/definitions/modules/dropdown.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#613 Checkbox fields
  src/definitions/collections/form.less
  src/themes/default/collections/form.variables
Labels: :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:

#641 [build] Task `watch` do not update files that depends on site.variable
  tasks/build/css.js
Labels: :electric_plug: build tools

#640 [Divider] Horizontal alignment for divider content
  src/definitions/elements/divider.less
Labels: :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:

#649 chore(probot): modify probot configs
  .github/auto_assign.yml
  .github/config.yml
Labels: :globe_with_meridians: platform

#648 fix(form): Remove unnecessary property '-webkit-appearance: none' with :focus from error field
  src/definitions/collections/form.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#661 [Form] Add dirty and clean states, and ability to cancel submit
  src/definitions/behaviors/form.js
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, lang: JavaScript :scroll:

#659 [Card] Force horizontal cards meta, extra content and actions to align properly
  src/definitions/views/card.less
Labels: :bug: bugfix, :eyes: needs reviewed, lang: CSS :art:

#657 [Dropdown] Hide a possible open menu on destroy for correct reset state
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#644 [Modal] Support fixed menu, toast and sidebar to also not move when a modal is shown
  src/definitions/modules/modal.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#646 [Button] Group of disabled basic button should have box-shadow
  src/definitions/elements/button.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#664 docs(readme): add jetbrains logo
  README.md
Labels: :page_facing_up: documents

#665 chore(probot): add all reviewers and add exoego as reviewer
  .github/auto_assign.yml
Labels: :globe_with_meridians: platform

#662 [Formvalidation] Make sure match/difference rules are selecting within the same form
  src/definitions/behaviors/form.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#658 fix(dropdown): margin missing when the position of floating menu of dropdown is upward
  src/definitions/modules/dropdown.less
Labels: :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:

#673 [Menu] Additional specificity for secondary inverted menu not necessary anymore
  src/definitions/collections/menu.less
Labels: :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:

#683 [Modal] Use direct sibling for content selector in overlay fullscreen modals
  src/definitions/modules/modal.less
Labels: :bug: confirmed bug, lang: CSS :art:

#698 fix(modal): open animation broken on first open
  src/definitions/modules/dropdown.js
  src/definitions/modules/transition.js
Labels: :bug: confirmed bug, lang: JavaScript :scroll:

#678 feat(form): add calendar input field
  src/definitions/behaviors/form.js
  src/definitions/modules/calendar.js
Labels: :triangular_ruler: needs doc changes, :zap: enhancement, lang: JavaScript :scroll:

#686 fix(*): breakpoints ignoring next breakpoint in some cases
  src/themes/default/globals/site.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#687 fix(calendar): string selectors for start/endCalendar did not work
  src/definitions/modules/calendar.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#677 feat(calendar): add eventDates support and onSelect handler
  src/definitions/modules/calendar.js
Labels: :bookmark_tabs: docs added, :zap: enhancement, lang: JavaScript :scroll:

#676 fix(tab): position issue with fixed item size
  src/definitions/collections/menu.less
Labels: :bug: bugfix, lang: CSS :art:

#702 feat(segment): add fitted variant
  src/definitions/elements/segment.less
Labels: :sleeping: sui issue, :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:

#704 fix(modal): `autofocus` shouldn’t focus disabled inputs
  src/definitions/modules/modal.js
Labels: :bug: confirmed bug, :sleeping: sui issue, lang: JavaScript :scroll:
