Repository fomantic/Fomantic-UI, pull requests merged in 2019-01, with the labels that each got.

#346 [Form,Segment] Inverted variants should get inverted loader properly
  src/definitions/collections/form.less
  src/definitions/elements/segment.less
  src/themes/default/collections/form.variables
  src/themes/default/elements/segment.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#339 [Dropdown] Fix simple dropdown positioning in vertical menus
  src/definitions/collections/menu.less
  src/definitions/modules/dropdown.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#347 [Menu] Corrected support for disabled items in inverted menus
  src/definitions/collections/menu.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#345 [Menu] Keep auto width for icon menu sizes
  src/definitions/collections/menu.less
Labels: :bug: confirmed bug, :sleeping: sui issue, lang: CSS :art:

#344 [Icon] Make "link" and "disabled" work together correctly
  src/definitions/elements/icon.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#343 [Search] Results with empty categories caused onSelect to return incorrect item
  src/definitions/modules/search.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#348 [Steps] feat(steps): Icon size variation
  src/definitions/elements/icon.less
Labels: :eyes: needs reviewed, :sleeping: sui issue, :zap: enhancement, lang: CSS :art:

#338 [Header] Attached inverted variant should have same background color as other inverted components
  src/themes/default/elements/header.variables
Labels: :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#350 [Popup] A Popup should have a higher z-index than a checkbox’s pin
  src/themes/default/modules/popup.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#355 [List] Add suffixed ordered list variation
  src/definitions/elements/list.less
  src/themes/default/elements/list.variables
Labels: :sleeping: sui issue, :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:

#359 [Loader,Modal] Default Loader color settings in Dimmers had impact on loaders in modals
  src/definitions/elements/loader.less
  src/definitions/modules/modal.less
  src/themes/default/modules/modal.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#358 [Dropdown]: Template for select-dropdown did not use classname-property from settings
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#356 [docs] code of conduct
  CODE_OF_CONDUCT.md
Labels: :globe_with_meridians: platform, :page_facing_up: documents

#337 [Label] Adjust image height of image labels in menu items
  src/definitions/collections/menu.less
  src/definitions/elements/label.less
  src/themes/default/collections/menu.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#332 [Table] Make colors work on striped, basic, selectable, stacked, definition
  src/definitions/collections/table.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#335 [Sidebar] Respect a change of closable setting
  src/definitions/modules/sidebar.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#360 [docs] add travis badge & change last commit branch
  README.md
Labels: :eyes: needs reviewed, :page_facing_up: documents

#361 [Button, Icon] Loading icon Position in Button was not rotating around center
  src/definitions/elements/button.less
  src/definitions/elements/icon.less
  src/themes/default/elements/button.variables
Labels: :bug: confirmed bug, :sleeping: sui issue, lang: CSS :art:

#363 [Loader] Elastic Loader was not working in Firefox
  src/definitions/elements/loader.less
Labels: :bug: bugfix, :eyes: needs reviewed, browser: firefox, lang: CSS :art:

#366 [Segment, Menu] "secondary segment" or "secondary menu" have a different meaning
  src/definitions/collections/menu.less
  src/definitions/elements/segment.less
Labels: :bug: bugfix, :eyes: needs reviewed, lang: CSS :art:

#381 [Dropdown] Cast to String before rendering if value is an integer
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#380 [Menu] Wrong Border for inverted pointing menu removed and fix for secondary as color
  src/definitions/collections/menu.less
Labels: :bug: bugfix, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#378 [Menu] Labels in secondary pointing menu items were misaligned
  src/definitions/collections/menu.less
  src/themes/default/collections/menu.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#372 [Formvalidation] Radio buttons do not validate if the first is disabled
  src/definitions/behaviors/form.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#371 [Dimmer] blurring dimmable leaves z-index stacking side effects
  src/themes/default/modules/dimmer.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#370 [Dropdown] Allow a real zero to be a selectable value in 'set selected'
  src/definitions/modules/dropdown.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#369 [Label] Link icon cursors in corner labels did not work
  src/definitions/elements/label.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#390 [Search] Removed wrong markup and added missing semicolons
  src/definitions/modules/search.js
Labels: :bug: bugfix, :eyes: needs reviewed, lang: JavaScript :scroll:

#397 [Step] make steps wrap by default as intended for single step
  src/definitions/elements/step.less
Labels: :eyes: needs reviewed, :sleeping: sui issue, :zap: enhancement, lang: CSS :art:

#388 [Label] Right icon should have correct margin when placed after text
  src/definitions/elements/label.less
Labels: :bookmark_tabs: docs added, :eyes: needs reviewed, :sleeping: sui issue, :zap: enhancement, lang: CSS :art:

#392 [Input] Make inverted transparent input in forms appear white
  src/definitions/elements/input.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: CSS :art:

#395 [Popup] correct tooltip z-index value
  src/themes/default/modules/popup.variables
Labels: :bug: bugfix, :eyes: needs reviewed, lang: CSS :art:

#409 [Menu] Increased color specificity to override secondary menu default colors
  src/definitions/collections/menu.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#389 [Dropdown] Use delete icon classname from settings instead of having it hardcoded
  src/definitions/modules/dropdown.js
Labels: :eyes: needs reviewed, :zap: enhancement, lang: JavaScript :scroll:

#404 [Label] Content in floating labels should not wrap whitespace
  src/definitions/elements/label.less
Labels: :eyes: needs reviewed, :sleeping: sui issue, :zap: enhancement, lang: CSS :art:

#414 [Text] Added sizes identically to icon
  src/definitions/elements/text.less
  src/themes/default/elements/text.variables
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:

#387 [Formvalidation] Input array validations should respect each single field on its own
  src/definitions/behaviors/form.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#357 [Transition] Remember inline style display and dont show hidden objects like <script>
  src/definitions/modules/accordion.js
  src/definitions/modules/transition.js
Labels: :bookmark_tabs: docs added, :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#412 [Progress] Fix 0% display and "inverted indicating" label color
  src/definitions/modules/progress.js
  src/definitions/modules/progress.less
  src/themes/default/modules/progress.variables
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:, lang: JavaScript :scroll:

#419 [Validation] Supply checked radio value to custom rule
  src/definitions/behaviors/form.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#425 [Progress] Don't show min-width progress bar when module was not initialized
  src/definitions/modules/progress.less
Labels: :bug: bugfix, :eyes: needs reviewed, lang: CSS :art:

#434 [Modal] Reactivate approve/deny event handling if onHide returned false
  src/definitions/modules/modal.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, :sleeping: sui issue, lang: JavaScript :scroll:

#398 [Segment] Introducing stackable horizontal segments
  src/definitions/elements/segment.less
Labels: :eyes: needs reviewed, :triangular_ruler: needs doc changes, :zap: enhancement, lang: CSS :art:

#403 [Checkbox] Call onChange only once and dont at all on "set checked" (and others)
  src/definitions/modules/checkbox.js
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: JavaScript :scroll:

#440 chore: remove gulp-help dependency
  gulpfile.js
  package-lock.json
  package.json
  tasks/build.js
  tasks/config/npm/gulpfile.js
Labels: :electric_plug: build tools

#438 [Icon] Increase color specificity
  src/definitions/elements/icon.less
Labels: :bug: confirmed bug, :eyes: needs reviewed, lang: CSS :art:

#437 [Modal] Prevent closing the modal when webkit scrollbar has been dragged
  src/definitions/modules/modal.js
Labels: :bookmark_tabs: docs added, :bug: confirmed bug, :eyes: needs reviewed, browser: chrome, lang: JavaScript :scroll:

#443 [Reset] Updated normalize.css to 8.0.1
  src/themes/default/globals/reset.overrides
Labels: :eyes: needs reviewed, :zap: enhancement, lang: CSS :art:
