Repository fomantic/Fomantic-UI, pull requests merged in 2020-05, with the labels that each got.

#1426 [Step] Right vertical steps variant having the arrow to te left side
  src/definitions/elements/step.less
  src/themes/default/elements/step.variables
Labels: lang/css, state/awaiting-reviews, state/has-docs, type/feat

#1329 [Calendar] Fire onchange only when date selection is complete
  src/definitions/modules/calendar.js
Labels: lang/javascript, state/awaiting-reviews, type/feat

#1439 [Calendar] Fix the popup show function getting called twice
  src/definitions/modules/calendar.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1350 [Enhancement]: [Search] Scrollable search result
  src/definitions/modules/search.js
  src/definitions/modules/search.less
  src/themes/default/globals/variation.variables
  src/themes/default/modules/search.variables
Labels: lang/javascript, state/awaiting-reviews, state/has-docs, type/feat

#1469 fix(build): double check for existing object property in tasks
  tasks/config/tasks.js
Labels: state/awaiting-reviews, type/bug, type/build

#1464 Add variable for divider border style
  src/definitions/elements/divider.less
  src/themes/default/elements/divider.variables
Labels: lang/css, state/awaiting-reviews, type/feat

#1471 [Dropdown]: Initial preselected values trigger onchange event
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1467 [Build] Support gulp calls to find semantic.json from outside fomantic folder
  tasks/config/user.js
  tasks/install.js
Labels: state/awaiting-reviews, type/build, type/feat

#1481 [Button] Correct vertical align for icons within buttons
  src/definitions/elements/button.less
  src/themes/default/elements/button.variables
Labels: lang/css, state/awaiting-reviews, type/bug

#1473 fix(dropdown): the nested dropdown menus do not behave correctly
  src/definitions/modules/dropdown.less
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1488 [Tab] Make auto activation of tabs optional
  src/definitions/modules/tab.js
Labels: lang/javascript, state/awaiting-reviews, state/has-docs, type/bug, type/feat
