Repository fomantic/Fomantic-UI, pull requests merged in 2020-10, with the labels that each got.

#1687 [Slider] No minimum step for label generator
  src/definitions/modules/slider.js
Labels: lang/javascript, state/awaiting-reviews, type/feat

#1693 [slider]: onChange is triggered without moving slider
  src/definitions/modules/slider.js
Labels: lang/javascript, state/awaiting-reviews, type/feat

#1696 Update ROADMAP.md
  ROADMAP.md
Labels: state/awaiting-reviews, type/chore

#1698 feat(chore): remove support issue template in favor of using discussions
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/support-question.md
Labels: state/awaiting-reviews, type/chore

#1695 [Form Validation] Set optional field behavior
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/feat

#1703 [Card] Images in horizontal cards are stretched on latest chrome when inside css table layout
  src/definitions/views/card.less
Labels: browser/chromium, lang/css, state/awaiting-reviews, type/bug

#1690 [Progress] limitValues setting limits values to 100 instead of percentages
  src/definitions/modules/progress.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1704 [Progress] Support right aligned progress bar
  src/definitions/modules/progress.less
  src/themes/default/globals/variation.variables
  src/themes/default/modules/progress.variables
Labels: lang/css, state/awaiting-reviews, state/has-docs, tag/sui-issue, type/feat

#1673 [Label,Form] Apply the error color not only to the label tag but also with label class
  src/definitions/collections/form.less
  src/themes/default/globals/colors.less
Labels: lang/css, state/awaiting-reviews, type/feat

#1706 [Calendar]: Support single digit months and days at parsing time
  src/definitions/modules/calendar.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1710 [Header] Icon content was not aligned
  src/definitions/elements/header.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1709 [Button] Support stackable buttons
  src/definitions/elements/button.less
  src/themes/default/globals/variation.variables
Labels: lang/css, state/awaiting-docs, state/awaiting-reviews, type/feat

#1713 [Form] Option errorfocus to auto focus the first error field on form validation
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, state/has-docs, type/feat

#1714 [Dropdown] show callback was ignored on remote api call
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1414 [Dropdown] apiSettings.cache=false, the whole list is not refresh by clicking on the down arrow icon
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1724 [Slider] Remove old dist files for renamed slider (previously "range")
  dist/components/range.css
  dist/components/range.js
  dist/components/range.min.css
  dist/components/range.min.js
Labels: state/awaiting-reviews, type/chore

#1727 [Slider] Fix bottom aligned labels for size variations
  src/definitions/modules/slider.less
Labels: lang/css, type/bug

#1725 [Dropdown] Menu did not show up on mobile when search and api was used (api was also called twice)
  src/definitions/modules/dropdown.js
Labels: device/mobile, lang/javascript, state/awaiting-reviews, type/bug
