Repository fomantic/Fomantic-UI, pull requests merged in 2020-02, with the labels that each got.

#1307 [Dropdown] Cursor in search field was barely visible when field has error class
  src/definitions/modules/dropdown.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1323 Replace all rule tokens in prompt message
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, type/feat

#1322 [Menu] Colored active items were not displayed colored
  src/definitions/collections/menu.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1240 [Modal] Return control over useflex again, but provide unsupported debug warning
  src/definitions/modules/modal.js
Labels: lang/javascript, state/awaiting-reviews, type/feat

#1298 [Form, Calendar] Calendar inline fields did not display properly
  src/definitions/collections/form.less
  src/themes/default/collections/form.variables
Labels: lang/css, type/bug

#1328 fix(form): make a difference between value 0 and false for radio buttons
  src/definitions/behaviors/form.js
Labels: lang/javascript, type/bug

#1330 [Calendar] Add ability to disable months and years
  src/definitions/modules/calendar.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/feat

#1342 fix(emoji): disabled link emoji should not have pointer cursor
  src/definitions/elements/emoji.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1334 [Table] Invented a helper class to solve the styling logic when rowspan is used in tables
  src/definitions/collections/table.less
Labels: lang/css, state/has-docs, tag/sui-issue, type/bug
