Repository fomantic/Fomantic-UI, pull requests merged in 2020-07, with the labels that each got.

#1550 [Form] Fields in field groups on mobile view had wrong bottom margin
  src/definitions/collections/form.less
Labels: device/mobile, lang/css, state/awaiting-reviews, type/bug

#1552 fix(site): duplicatedVariables
  src/themes/default/globals/site.variables
Labels: lang/css, state/awaiting-reviews, tag/sui-issue, type/bug

#1561 [Dimmer] opacity setting created invalid value on rgb background
  src/definitions/modules/dimmer.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1555 [Dimmer] Support more background types than only color
  src/definitions/modules/dimmer.less
  src/definitions/modules/sidebar.less
  src/definitions/views/card.less
Labels: lang/css, state/awaiting-reviews, type/feat

#1569 [Calendar] Chrome chooses wrong hour on time-only calendar
  src/definitions/modules/calendar.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1568 [List] icon buttons were misaligned
  src/definitions/elements/list.less
Labels: lang/css, state/awaiting-reviews, tag/sui-issue, type/bug

#1563 [Calendar] Evenly divide column widths
  src/definitions/modules/calendar.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1571 [Button] compact icon button had wrong padding
  src/definitions/elements/button.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1564 [Text] support state colors
  src/definitions/elements/text.less
  src/themes/default/globals/colors.less
  src/themes/default/globals/variation.variables
Labels: lang/css, state/awaiting-reviews, state/has-docs, type/feat

#1578 [Popup] Remove text-shadow explicitly on tooltip to avoid inheritance from parent
  src/definitions/modules/popup.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1587 [Button] Dedicated variables for toggle and circular variants
  src/definitions/elements/button.less
  src/themes/default/elements/button.variables
Labels: lang/css, state/awaiting-reviews, type/feat

#1585 [Segment]: Horizontal segments' rounded corner
  src/definitions/elements/segment.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1589 [Table] Change default vertical alignment of table footer
  src/themes/default/collections/table.variables
Labels: lang/css, state/awaiting-reviews, type/bug

#1593 [Icon/Button] Make sure real icon selectors are addressed
  src/definitions/collections/menu.less
  src/definitions/collections/message.less
  src/definitions/collections/table.less
  src/definitions/elements/header.less
  src/definitions/elements/input.less
  src/definitions/elements/step.less
  src/definitions/modules/calendar.less
  src/definitions/modules/dropdown.less
  src/definitions/modules/embed.less
  src/definitions/modules/modal.less
  src/definitions/modules/toast.less
  src/definitions/views/feed.less
  src/definitions/views/statistic.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1596 [Calendar] Adjust cell tooltip positions according to popup position to avoid it being hidden
  src/definitions/modules/calendar.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1601 [Toast] Fix the toast error progress bar visibility
  src/definitions/modules/toast.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1597 [Calendar]: Inverted Variant
  src/definitions/modules/calendar.js
  src/definitions/modules/calendar.less
  src/themes/default/globals/variation.variables
  src/themes/default/modules/calendar.variables
Labels: lang/css, lang/javascript, state/awaiting-reviews, state/has-docs, type/feat

#1602 [Calendar] trigger native change event on date selection
  src/definitions/modules/calendar.js
  src/definitions/modules/checkbox.js
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1618 fix(image): Support the image to be centered when using a different H…
  src/definitions/elements/image.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1617 [Form] Adjust checkbox margins in grouped inline fields for nice distance of error prompts
  src/definitions/collections/form.less
  src/themes/default/collections/form.variables
Labels: lang/css, state/awaiting-reviews, type/feat

#1611 [Form]: Remove existing error messages on clear and reset and adjust error messages on revalidation when not inline
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, tag/sui-issue, type/bug

#1622 [Sidebar] Avoid scrollbar on non body pushable (visible on bottom sidebars)
  src/definitions/modules/sidebar.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1615 [Form] isValid should not delete error state
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, state/has-docs, type/bug

#1612 [Form] dirty state check failed for multiple variant of native select tag
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, type/bug
