Repository fomantic/Fomantic-UI, pull requests merged in 2020-03, with the labels that each got.

#1353 Update visibility.js
  src/definitions/behaviors/visibility.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1358 [build] fix the minified css build
  tasks/build/css.js
Labels: state/awaiting-reviews, type/bug, type/build

#1372 [Icon] medium/default font was missing general css properties
  src/definitions/elements/icon.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1378 [Input] Better differ between left/right icon/action
  src/definitions/collections/form.less
  src/definitions/elements/input.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1379 fix(search) Fix padding it description when search inside modal
  src/definitions/modules/modal.less
Labels: lang/css, state/awaiting-reviews, type/bug
