Repository fomantic/Fomantic-UI, pull requests merged in 2020-04, with the labels that each got.

#1346 [Form Validation] fix "disabled" detection
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews

#1385 [Build] Allow individual components to be defined in config
  tasks/build/css.js
  tasks/build/javascript.js
  tasks/config/project/config.js
Labels: state/awaiting-reviews, state/has-docs, type/build, type/feat

#1406 [Modal] Center fluid action buttons correctly
  src/definitions/modules/modal.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1398 [Dropdown] Prevent showing the whole list if showOnFocus is false
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1415 fix(chore): replace jquery trim method with vanilla javascript (deprecated as of jq 3.5)
  src/definitions/behaviors/form.js
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/chore

#1408 Prevent gulp watch task from refreshing all components
  tasks/build/css.js
  tasks/build/javascript.js
Labels: state/awaiting-reviews, type/bug, type/build

#1419 fix(build): Import 'various' gulp tasks
  tasks/config/npm/gulpfile.js
Labels: state/awaiting-reviews, type/build, type/feat

#1412 [Button Animated] Adjust vertical-align for icons & support ui.animated.icon.button
  src/definitions/elements/button.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1428 [Progress bar] indicating background color is incorrect when data-percent have decimal number
  src/definitions/modules/progress.less
Labels: lang/css, state/awaiting-reviews, type/bug
