Repository fomantic/Fomantic-UI, pull requests merged in 2020-11, with the labels that each got.

#1739 [Grid] stackable grid had wrong width inside popup
  src/definitions/collections/grid.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1736 [Icon] Labels in icon groups where shown italic
  src/definitions/elements/icon.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1735 [Calendar] Show active and eventdates on enabled adjacent days
  src/definitions/modules/calendar.js
  src/definitions/modules/calendar.less
Labels: lang/css, lang/javascript, state/awaiting-reviews, type/bug

#1743 fix(chore): use url encoded semicolons so gulp-concat doesnt break
  src/themes/default/globals/site.variables
Labels: state/awaiting-reviews, type/build, type/chore

#1749 [Icon] Make colored icon selector more specific
  src/definitions/elements/icon.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1751 [Slider] support control over change trigger when setting a value or range
  src/definitions/modules/slider.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/feat

#1755 [Icons] allow corner icons and icon groups to be bordered
  src/definitions/elements/icon.less
  src/themes/default/elements/icon.variables
Labels: lang/css, state/awaiting-docs, state/awaiting-reviews, type/feat

#1757 fix(chore): Fetch correct milestones for nightly beta build
  scripts/nightly-version.js
Labels: state/awaiting-reviews, type/build, type/chore

#1758 [Table] Allow pointer events for the first header cell in definition table
  src/definitions/collections/table.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1760 [Card] Fix the top border thickness of horizontal card
  src/definitions/views/card.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1761 [Card]: Inverted header links were not styled properly
  src/definitions/views/card.less
  src/themes/default/views/card.variables
Labels: lang/css, state/awaiting-reviews, type/bug

#1762 [Card] Disabled and loading variants just like segment
  src/definitions/elements/loader.less
  src/definitions/views/card.less
  src/themes/default/globals/variation.variables
  src/themes/default/views/card.variables
Labels: lang/css, state/awaiting-docs, state/awaiting-reviews, type/feat

#1764 [Segment] Prevent user selection on disabled and loading segments
  src/definitions/elements/segment.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1766 feat(dropdown): support icon groups margin
  src/definitions/modules/dropdown.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1770 [Dropdown] multiselect values encoding, label cannot be removed, quotes missing in select dropdown
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1773 [Toast] horizontal variant and dynamic DOM node content support
  src/definitions/modules/toast.js
  src/definitions/modules/toast.less
  src/themes/default/globals/variation.variables
  src/themes/default/modules/toast.variables
Labels: lang/css, lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/feat

#1774 feat(modal): dynamic modal content
  src/definitions/modules/modal.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/feat

#1775 [Modal] Centered variant for any content
  src/definitions/modules/modal.less
  src/themes/default/modules/modal.variables
Labels: lang/css, state/awaiting-docs, state/awaiting-reviews, type/feat

#1777 fix(calendar): return null instead of undefined in sanitizer
  src/definitions/modules/calendar.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1782 fix(dropdown): Clearing multiple selection dropdown supports to prevent onChange callback
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1779 fix(dropdown): calculate correct height of current menu if it contains child menu
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/bug
