Repository fomantic/Fomantic-UI, pull requests merged in 2020-08, with the labels that each got.

#1627 [Form] Reset submitting flag when validation fails to keep dirtycheck with preventLeaving setting
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1613 [Chore] fix cdn default js file
  package.json
Labels: state/awaiting-reviews, type/chore

#1631 feat(slider): prevent line break in slider label and support bottom aligned label
  src/definitions/modules/slider.less
  src/themes/default/modules/slider.variables
Labels: lang/css, state/awaiting-reviews, type/feat

#1606 [Dropdown, Calendar] Pressing tab entered disabled dropdown/calendar fields
  src/definitions/modules/calendar.js
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1567 [Progress ]Total value of 0 was unsupported and fix limitValues
  src/definitions/modules/progress.js
Labels: lang/javascript, state/awaiting-reviews, tag/sui-issue, type/bug

#1636 fix(icon): Change two-word aliases into one-word aliases to avoid conflictions
  src/themes/default/elements/icon.overrides
Labels: lang/css, state/awaiting-reviews, type/bug

#1637 feat(icon): add the old two classes for linegraph and chartline for c…
  src/themes/default/elements/icon.overrides
Labels: lang/css, state/awaiting-reviews, type/feat

#1639 [Build] Fix issue when "individuals" or "components" has only single element
  tasks/config/project/config.js
Labels: state/awaiting-reviews, type/bug, type/build

#1643 feat(docs): added openbase.io badge
  README.md
Labels: state/awaiting-reviews, type/docs

#1641 [Build] Remove individuals from components so users can specify only individuals
  tasks/config/project/config.js
Labels: state/awaiting-reviews, state/has-docs, type/build

#1629 [Dropdown] Use configured 'fields.values' key instead of fixed 'values'
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1647 [Calendar] Support safari to accept yyyy-mm-dd format using dashes
  src/definitions/modules/calendar.js
Labels: browser/safari, lang/javascript, state/awaiting-reviews, type/bug

#1653 [Search] Avoid unnecessary double link navigation
  src/definitions/modules/search.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1655 [Site] greyhover and blackhover are declared twice
  src/themes/default/globals/site.variables
Labels: lang/css, state/awaiting-reviews, type/bug

#1661 [Form] Dont bind events to dropdown search inputs to prevent jquery 3.4 callstack error
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1662 [Docs] add web components to library implementations
  ROADMAP.md
Labels: state/awaiting-reviews, tag/v3, type/docs

#1656 [Dropdown] Multiple search button dropdown misaligned, placeholder wraps and search text ghosting
  src/definitions/modules/dropdown.less
Labels: lang/css, state/awaiting-reviews, type/bug
