Repository fomantic/Fomantic-UI, pull requests merged in 2020-06, with the labels that each got.

#1435 chore(readme): add do sponsor content
  README.md
Labels: state/awaiting-reviews, type/chore

#1496 [dropdown] Fix a sizer element being created every time dropdown is initialized
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1497 fix(build): missing extra parameter for current directory in release task leads into missing build number
  tasks/config/project/release.js
Labels: state/awaiting-reviews, type/bug, type/build

#1491 fix(dimmer): page dimmer in firefox results in misaligned modals
  src/definitions/modules/dimmer.less
Labels: browser/firefox, lang/css, state/awaiting-reviews, type/bug

#1516 feat(chore): autoassign ko2in for pr reviews
  .github/auto_assign.yml
Labels: state/awaiting-reviews, type/feat

#1513 [Transition/Chore] Make effects optional for CSS compilation
  src/themes/default/globals/variation.variables
  src/themes/default/modules/transition.overrides
Labels: lang/css, state/awaiting-reviews, type/build, type/feat

#1505 fix(dropdown): fix some bugs introduce by the previous commit (#1473)
  src/definitions/modules/dropdown.less
  src/themes/default/modules/dropdown.variables
Labels: lang/css, priority/high, state/awaiting-reviews, type/bug

#1503 [Icon,Text] Fix vertical alignment
  src/definitions/elements/icon.less
  src/definitions/elements/text.less
  src/themes/default/elements/icon.variables
  src/themes/default/elements/text.variables
Labels: lang/css, state/awaiting-reviews, type/bug

#1507 [Label] Basic Labels had different height and adjusted (attached) image labels
  src/definitions/elements/label.less
  src/themes/default/elements/label.variables
Labels: lang/css, state/awaiting-reviews, type/bug

#1528 [Slider] interpretLabel is undefined instead of false by default
  src/definitions/modules/slider.js
Labels: lang/javascript, state/awaiting-reviews, type/feat

#1533 [Dropdown] Columnar dropdowns were not working on raw div dropdowns
  src/definitions/modules/dropdown.js
  src/definitions/modules/dropdown.less
Labels: lang/css, lang/javascript, state/awaiting-reviews, type/bug

#1540 Fixed 2 instances of spelling issues
  ROADMAP.md
Labels: type/docs

#1536 [Menu] Fix icon group position and alignment in submenus
  src/definitions/collections/menu.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1546 [Icon] Numeric classname `stopwatch.20` since font aweseome 5.13
  src/themes/default/elements/icon.overrides
Labels: lang/css, state/awaiting-reviews, type/bug

#1543 [Dropdown] HTML in placeholders was not preserved
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1537 [Popup] left/right center tooltips were misaligned on Firefox (posix)
  src/definitions/modules/popup.less
Labels: browser/firefox, lang/css, state/awaiting-reviews, type/bug

#1531 [Calendar] Avoid unnecessary redraw which slows down the module
  src/definitions/modules/calendar.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1547 [Slider] operation sometimes returns not rounded value
  dist/components/slider.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1548 [Slider] operation sometimes returns not rounded value #1547
  src/definitions/modules/slider.js
Labels: lang/javascript, state/awaiting-reviews, type/bug
