Repository fomantic/Fomantic-UI, pull requests merged in 2020-12, with the labels that each got.

#1784 [Button] labeled icon buttons have wrong margin
  src/definitions/elements/button.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1790 fix(table): missing comma lead into wrong selector
  src/definitions/collections/table.less
Labels: lang/css, type/bug

#1793 feat(dropdown): support inverted menu in non-inverted dropdown
  src/definitions/modules/dropdown.less
Labels: lang/css, state/awaiting-docs, type/feat

#1794 fix(grid): incorrect margins in compact and very compact grid
  src/definitions/collections/grid.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1797 [Input / Form] Firefox has different placeholder opacity by default
  src/definitions/collections/form.less
  src/definitions/elements/input.less
Labels: browser/firefox, lang/css, state/awaiting-reviews, tag/sui-issue, type/bug

#1799 [Header] Support icon groups
  src/definitions/elements/header.less
Labels: lang/css, state/awaiting-reviews, tag/sui-issue, type/bug

#1798 [Message] Support icon groups
  src/definitions/collections/message.less
Labels: lang/css, state/awaiting-reviews, tag/sui-issue, type/bug

#1796 [Form]: Support range values for decimal and number validation, add max/minValue and display range in default prompt
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, tag/sui-issue, type/feat

#1803 [Dropdown / Form] Item text with descriptions gets wrong state class
  src/definitions/collections/form.less
Labels: lang/css, state/awaiting-reviews, tag/sui-issue, type/bug

#1801 [Tooltip] Bottom center tooltip was misaligned
  src/definitions/modules/popup.less
Labels: lang/css, state/awaiting-reviews, tag/sui-issue, type/bug

#1800 [Message] centered and right aligned variant
  src/definitions/collections/message.less
  src/themes/default/globals/variation.variables
Labels: lang/css, state/awaiting-docs, state/awaiting-reviews, tag/sui-issue, type/feat

#1806 [Checkbox, Dropdown] Support and fix read only variant
  src/definitions/modules/checkbox.less
  src/definitions/modules/dropdown.less
  src/themes/default/globals/variation.variables
Labels: lang/css, state/awaiting-docs, state/awaiting-reviews, tag/sui-issue, type/bug, type/feat

#1809 [Form] Simplify Blur validation and respect revalidate:false
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, tag/sui-issue, type/bug

#1811 [Form] Refresh on instance rather than module to fetch dom changes
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, tag/sui-issue, type/bug

#1807 [Dropdown] Clearable inline support
  src/definitions/modules/dropdown.js
  src/definitions/modules/dropdown.less
  src/themes/default/modules/dropdown.variables
Labels: lang/css, lang/javascript, state/awaiting-reviews, tag/sui-issue, type/bug

#1795 [Nag] Refactored: no jquery cookie plugin dependency, colors, sizes, fixes
  src/definitions/modules/nag.js
  src/definitions/modules/nag.less
  src/themes/default/globals/variation.variables
  src/themes/default/modules/nag.variables
Labels: lang/css, lang/javascript, state/awaiting-docs, state/awaiting-reviews, tag/sui-issue, type/bug, type/feat

#1808 [Icon] Support transformations in icon groups
  src/definitions/elements/icon.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1805 [Toast] Top/Bottom attached position variant and centered support
  src/definitions/modules/toast.less
  src/themes/default/globals/variation.variables
  src/themes/default/modules/toast.variables
Labels: lang/css, state/awaiting-docs, state/awaiting-reviews, type/feat

#1810 [Form] Support mix of shorthand and full object field rules
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, tag/sui-issue, type/bug

#1813 fix(build): upgrade css minify and remove specialcomments in concat build
  package-lock.json
  package.json
  tasks/config/tasks.js
Labels: state/awaiting-reviews, tag/sui-issue, type/build

#1812 fix(build): use current year and implement version in header
  package-lock.json
  package.json
  tasks/config/project/release.js
  tasks/config/tasks.js
Labels: state/awaiting-reviews, type/build

#1814 [Form] Support shouldtrim option per fieldrule
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/feat

#1815 feat(icon): use corner offset variables
  src/definitions/elements/icon.less
  src/themes/default/elements/icon.variables
Labels: lang/css, state/awaiting-reviews, type/feat

#1819 [Chore] Added parenthesis to math divisions to support LESS 4
  src/definitions/collections/form.less
  src/definitions/collections/grid.less
  src/definitions/modules/slider.less
  src/themes/default/collections/grid.variables
  src/themes/default/collections/table.variables
  src/themes/default/elements/header.variables
  src/themes/default/elements/list.variables
  src/themes/default/globals/site.variables
  src/themes/default/modules/checkbox.variables
  src/themes/default/modules/dropdown.variables
  src/themes/default/modules/modal.variables
  src/themes/default/views/card.variables
Labels: lang/css, state/awaiting-reviews, type/chore

#1816 [Modal] bodyfixed selector did not work with existing padding values
  src/definitions/modules/modal.js
Labels: lang/javascript, state/awaiting-reviews, type/bug
