Repository fomantic/Fomantic-UI, pull requests merged in 2020-01, with the labels that each got.

#1245 [Checkbox] dont show visual changes on disabled checkboxes
  src/definitions/modules/checkbox.less
Labels: lang/css, state/awaiting-reviews, type/feat

#1266 fix(dropdown): get item function now working properly with array of i…
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1262 fix(segment): sub headers in inverted segments were not changed to white when inside content div of header
  src/definitions/elements/segment.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1249 [Modal] Basic Modal header should not have a border
  src/definitions/modules/modal.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1275 [Modal] Border radius for inner dimmer should inherit from the modal
  src/definitions/modules/modal.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1248 build(config): respect browserslist config
  tasks/config/tasks.js
Labels: type/build, type/feat

#1264 [Toast ]Make sure element does still exist before transition ends
  src/definitions/modules/toast.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1244 [Form] Auto add empty rule validation for required fields
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/feat

#1284 [Shape] make sure chrome renders the z-translated faces properly
  src/definitions/modules/shape.less
Labels: browser/chromium, lang/css, state/awaiting-reviews, type/bug
