Repository fomantic/Fomantic-UI, pull requests merged in 2020-09, with the labels that each got.

#1651 [Dropdown] optional show a scrollhint on ios devices (or firefox mobile) to indicate more entries
  src/definitions/modules/dropdown.less
  src/themes/default/globals/variation.variables
  src/themes/default/modules/dropdown.variables
Labels: browser/firefox, browser/safari, device/mobile, lang/css, state/awaiting-docs, state/awaiting-reviews

#1614 [Input,Form] Action or labeled inputs in grouped fields were not styled properly with state classes
  src/definitions/elements/input.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1664 [Dropdown] "very short" menu height always overriden by normal "short" height because of wrong specificity order
  src/definitions/modules/dropdown.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1116 feature(dropdown): Allows vertical dropdown menu item content
  src/definitions/modules/dropdown.less
  src/themes/default/modules/dropdown.variables
Labels: lang/css, lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/feat

#1670 [Checkbox] Support right aligned position of checkbox variants
  src/definitions/modules/checkbox.less
  src/themes/default/globals/variation.variables
  src/themes/default/modules/checkbox.variables
Labels: lang/css, state/awaiting-reviews, state/has-docs, type/feat

#1669 feat(dropdown): Dropdown formatted with label like input labeled
  src/definitions/modules/dropdown.less
Labels: lang/css, state/awaiting-docs, state/awaiting-reviews, type/feat

#1672 [Dropdown] Allow displayType transition setting to be overriden by dropdown
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/bug

#1674 [Chore] Update google fonts api to v2
  src/theme.less
  src/themes/default/globals/site.variables
Labels: lang/css, state/awaiting-reviews, tag/sui-issue, type/feat

#1683 [Dropdown] Add `preventChangeTrigger` parameter to the `set selected` behavior
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, state/has-docs, type/feat

#1686 [Slider] - With step 0, divides by 0
  src/definitions/modules/slider.js
Labels: lang/javascript, type/bug

#1681 fix(dropdown) - forceSelection trigger event with null addition
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/bug
