Repository fomantic/Fomantic-UI, pull requests merged in 2021-07, with the labels that each got.

#2001 feat(calendar): trigger onSelect() event on enter key down
  src/definitions/modules/calendar.js
Labels: lang/javascript, type/feat

#2003 feat(dimmer): add onVisible and onHidden callbacks
  src/definitions/modules/dimmer.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/feat

#2000 fix(calendar): arrow keys on endCalendar when startCal has future month
  src/definitions/modules/calendar.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#2011 fix(docs): various typos
  CONTRIBUTING.md
  dist/components/dropdown.js
  dist/components/menu.css
  dist/components/progress.js
  dist/components/transition.js
  dist/components/visibility.js
  dist/semantic.css
  dist/semantic.js
  examples/assets/library/iframe-content.js
  examples/assets/library/iframe.js
  src/definitions/behaviors/api.js
  src/definitions/behaviors/visibility.js
  src/definitions/collections/menu.less
  src/definitions/modules/dropdown.js
  src/definitions/modules/progress.js
  src/definitions/modules/sticky.js
  src/definitions/modules/transition.js
  tasks/admin/components/init.js
  tasks/admin/distributions/init.js
Labels: state/awaiting-reviews, type/docs

#2005 feat(calendar): disabledhours
  src/definitions/modules/calendar.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/feat

#2006 feat(toast): new centered variant to display in the middle of the screen
  src/definitions/modules/toast.less
  src/themes/default/globals/variation.variables
Labels: lang/css, state/awaiting-docs, state/awaiting-reviews, type/feat

#2021 fix(tooltip): fix arrow position for bottom center
  src/definitions/modules/popup.less
Labels: lang/css, state/awaiting-reviews, type/bug

#2023 fix(rating): partial rating needs webkit prefix
  src/definitions/modules/rating.less
  src/themes/default/globals/variation.variables
Labels: browser/chromium, lang/css, state/awaiting-reviews, type/bug

#2028 fix(step): unnecessary semicolon breaks webpack build
  src/themes/default/elements/step.overrides
Labels: lang/css, type/bug, type/typo, type/upstream

#2002 fix(calendar): blur input on hidden
  src/definitions/modules/calendar.js
Labels: lang/javascript, state/awaiting-reviews, type/feat
