Repository fomantic/Fomantic-UI, pull requests merged in 2021-05, with the labels that each got.

#1962 feat(build): check node 13 and 14 for github actions
  .github/workflows/ci.yml
Labels: state/awaiting-reviews, type/build

#1965 fix(search): fetch "Cannot read property 'top' of undefined
  src/definitions/modules/search.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1924 fix(segment): support placeholder segments for tab usage
  src/definitions/elements/segment.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1909 fix(header): icon headers should not have a left content padding
  src/definitions/elements/header.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1906 feat(validation): allow credit card numbers with spaces
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, type/feat

#1928 fix(calendar): disabled week days should not affect month and year view
  src/definitions/modules/calendar.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1950 fix(form): file upload fields trigger error using jquery > 3.4.0
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1957 fix(form): separate dirty events trigger multiple native event calls
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1966 feat(dropdown,popup): support individual show and hide transition and duration
  src/definitions/modules/dropdown.js
  src/definitions/modules/popup.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, tag/sui-issue, type/feat

#1969 feat(segment): support equal width
  src/definitions/elements/segment.less
Labels: lang/css, state/awaiting-docs, state/awaiting-reviews, tag/sui-issue, type/feat

#1973 fix(rating): disabled rating should not allow pointer events
  src/definitions/modules/rating.less
Labels: lang/css, state/awaiting-reviews, type/bug
