Repository fomantic/Fomantic-UI, pull requests merged in 2021-01, with the labels that each got.

#1821 feat(dropdown): support submenu values
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/feat

#1822 fix(progress): adjust center position
  src/definitions/modules/progress.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1829 fix(form): refresh module on re-initializaion
  src/definitions/behaviors/form.js
Labels: lang/javascript, priority/high, state/awaiting-reviews, type/bug

#1830 fix(docs): grammar error
  README.md
Labels: type/docs

#1828 fix(form): inverted state forms colors
  src/definitions/collections/form.less
  src/definitions/collections/message.less
  src/themes/default/globals/colors.less
  src/themes/default/globals/site.variables
Labels: lang/css, state/awaiting-reviews, type/bug

#1833 fix(colors): compile error of php less port
  src/themes/default/globals/colors.less
Labels: lang/css, state/awaiting-reviews, type/bug

#1836 fix(toast): attached toast margin and border
  src/definitions/modules/toast.less
  src/themes/default/modules/toast.variables
Labels: lang/css, state/awaiting-reviews, type/bug

#1823 fix(nag): missing callbacks and fixed unused code
  src/definitions/modules/nag.js
Labels: lang/javascript, state/awaiting-reviews, state/has-docs, type/bug

#1844 feat(segment): disabled, inverted and loading groups
  src/definitions/elements/loader.less
  src/definitions/elements/segment.less
Labels: lang/css, state/awaiting-reviews, type/feat

#1856 feat(icon): colored variant for bordered or circular
  src/definitions/elements/icon.less
  src/themes/default/elements/icon.variables
  src/themes/default/globals/variation.variables
Labels: lang/css, state/awaiting-docs, state/awaiting-reviews, type/feat

#1853 feat(dropdown) adds onSearch callback for when searching in the dropdown
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-docs, state/awaiting-reviews, type/feat

#1852 feat(dropdown): addition of (vertical) descriptions to menu item template
  src/definitions/modules/dropdown.js
Labels: lang/javascript, state/awaiting-reviews, type/feat
