Repository fomantic/Fomantic-UI, pull requests merged in 2021-08, with the labels that each got.

#2012 fix(api): source typos
  examples/assets/library/iframe-content.js
  src/definitions/behaviors/api.js
  test/helpers/sinon.js
Labels: state/awaiting-reviews, tag/breaking-change, type/typo

#2022 fix(toast): dedicated horizontal container
  src/definitions/modules/toast.js
Labels: lang/javascript, state/awaiting-reviews, type/bug

#1744 fix(checkbox): remove the change trigger for enable and disable behavior
  src/definitions/modules/checkbox.js
Labels: type/feat, lang/javascript, tag/breaking-change

#2034 fix(dropdown): observe select attribute changes
  src/definitions/modules/dropdown.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2038 fix(form): avoid double submit on enterkey
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, tag/sui-issue

#1626 feat(form): optional support all field errors in inline prompt
  src/definitions/behaviors/form.js
  src/definitions/collections/form.less
Labels: type/feat, lang/javascript, state/on-hold, tag/breaking-change

#1508 fix(calendar): change to listen to click event by default
  src/definitions/modules/calendar.js
Labels: type/feat, lang/javascript, state/on-hold, state/has-docs, tag/breaking-change

#2036 feat(modal): a11y support, tabbing in modal, close icon focus/keypress
  src/definitions/modules/modal.js
  src/definitions/modules/modal.less
Labels: type/feat, lang/css, lang/javascript, state/awaiting-reviews, tag/sui-issue

#1747 feat(dropdown): change forceSelection default to false
  src/definitions/modules/dropdown.js
Labels: type/feat, lang/javascript, state/awaiting-docs, state/on-hold, tag/breaking-change

#1416 feat(segment): border to top instead of bottom for vertical variant
  src/definitions/elements/segment.less
Labels: type/feat, lang/css, tag/breaking-change

#1440 feat(button): split tertiarylinepadding variable
  src/definitions/elements/button.less
  src/themes/default/elements/button.variables
Labels: type/feat, lang/css, tag/breaking-change

#1562 feat(icon): make fontface import and icons optional separately
  src/definitions/elements/icon.less
  src/themes/default/elements/icon.overrides
  src/themes/default/elements/icon.variables
  src/themes/default/globals/variation.variables
Labels: type/feat, repo/css, tag/breaking-change

#1190 [Flag] use emoji flags with (auto) sizing
  src/definitions/elements/flag.less
  src/themes/default/elements/flag.overrides
  src/themes/default/elements/flag.variables
  src/themes/famfamfam/elements/flag.overrides
  src/themes/famfamfam/elements/flag.variables
Labels: type/feat, lang/css, state/on-hold, state/has-docs, tag/breaking-change

#2042 feat(dropdown): new default exact for fulltextsearch
  src/definitions/modules/dropdown.js
Labels: type/feat, lang/javascript, state/awaiting-reviews, state/has-docs, tag/breaking-change

#2046 fix(dropdown): add namespace to sessionstorage
  src/definitions/modules/dropdown.js
Labels: type/bug, lang/javascript, state/awaiting-reviews, tag/sui-issue

#2044 feat(dropdown): new default showonfocus false
  src/definitions/modules/dropdown.js
Labels: type/feat, lang/javascript, state/awaiting-reviews, state/has-docs, tag/breaking-change

#2051 feat(accordion): add compact and very compact variations
  src/definitions/modules/accordion.less
  src/themes/default/globals/variation.variables
  src/themes/default/modules/accordion.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/awaiting-docs

#2052 feat(form): support month, week and color input
  src/definitions/collections/form.less
  src/definitions/elements/input.less
Labels: type/feat, lang/css, state/awaiting-reviews

#2053 Update dependabot badge
  README.md
Labels: type/chore

#2054 fix(checkbox): show pointer on css only linked labels
  src/definitions/modules/checkbox.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2076 fix(dropdown): non selection and button upward variant border radius
  src/definitions/modules/dropdown.less
  src/themes/default/modules/dropdown.variables
Labels: lang/css, state/awaiting-reviews, tag/breaking-change

#2048 fix(form): dont focus errorfield on blur or change
  src/definitions/behaviors/form.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2041 feat(form): new default true for errorfocus
  src/definitions/behaviors/form.js
Labels: type/feat, lang/javascript, state/has-docs, tag/breaking-change

#2047 fix(api): respect post vars for caching
  src/definitions/behaviors/api.js
Labels: type/bug, lang/javascript, state/awaiting-reviews, tag/sui-issue

#2077 feat(checkbox): detect on as checked and add checkbox string values
  src/definitions/behaviors/form.js
Labels: type/feat, lang/javascript, state/awaiting-reviews, tag/sui-issue

#1480 fix(segment): tabular menu border misaligned from 3rd tab
  src/definitions/collections/menu.less
Labels: type/bug, lang/css, state/awaiting-docs, tag/breaking-change

#2078 feat(grid): stretched rows not broken on tablet size
  src/definitions/collections/grid.less
Labels: type/bug, lang/css, state/awaiting-reviews, tag/sui-issue

#2079 feat(segment):larger margin only for tab attached segment
  src/definitions/elements/segment.less
Labels: type/bug, lang/css, state/awaiting-reviews, tag/sui-issue

#2084 fix(menu): attached text menu had borders
  src/definitions/collections/menu.less
  src/definitions/elements/segment.less
Labels: type/bug, lang/css, state/awaiting-reviews, tag/sui-issue

#2083 feat(menu): centered variant
  src/definitions/collections/menu.less
  src/themes/default/globals/variation.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/awaiting-docs, tag/sui-issue

#2090 fix(table): links in compact selectable table cell get wrong padding
  src/definitions/collections/table.less
Labels: type/bug, lang/css, state/awaiting-reviews, tag/sui-issue

#2089 fix(form): keep a compact dropdown compact
  src/definitions/collections/form.less
Labels: type/bug, lang/css, state/awaiting-reviews, tag/sui-issue

#2085 feat(input): support invalid pseudoclass
  src/definitions/collections/form.less
  src/definitions/elements/input.less
Labels: type/feat, lang/css, state/awaiting-reviews, state/awaiting-docs, tag/sui-issue

#2082 fix(menu): inverted tabular menu styling should match tab
  src/definitions/collections/menu.less
  src/themes/default/collections/menu.variables
Labels: type/bug, lang/css, state/awaiting-reviews, tag/sui-issue
