Repository fomantic/Fomantic-UI, pull requests merged in 2021-11, with the labels that each got.

#2145 feat(input): file input variant
  src/definitions/collections/form.less
  src/definitions/elements/input.less
  src/themes/default/elements/input.variables
  src/themes/default/globals/variation.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/awaiting-docs, tag/sui-issue, hacktoberfest-accepted

#2148 feat(table): all scroll stuck head foot first last variant
  src/definitions/collections/table.less
  src/definitions/elements/container.less
  src/definitions/elements/segment.less
  src/themes/default/collections/table.variables
  src/themes/default/elements/container.variables
  src/themes/default/elements/segment.variables
  src/themes/default/globals/variation.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/awaiting-docs

#2150 fix(table): sortable border only when celled
  src/definitions/collections/table.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2158 fix(tab): initializing active tab with historytype 'state'
  src/definitions/modules/tab.js
Labels: lang/javascript, state/awaiting-reviews

#2162 fix(dropdown): onChange is fired on menu openeing when reselection=true
  src/definitions/modules/dropdown.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2164 feat(tab): callback to support tab change cancel
  src/definitions/modules/tab.js
Labels: type/feat, lang/javascript, state/awaiting-reviews, state/awaiting-docs

#2163 fix(segment): ignore attached border when basic
  src/definitions/elements/segment.less
Labels: type/bug, lang/css, state/awaiting-reviews
