Repository fomantic/Fomantic-UI, pull requests merged in 2021-09, with the labels that each got.

#2097 feat(chore): same custom scrollbars in chrome, FF and IE
  src/definitions/globals/site.less
  src/definitions/modules/dimmer.less
  src/definitions/modules/dropdown.less
  src/themes/default/globals/site.variables
Labels: type/feat, lang/css, state/awaiting-reviews, browser/ie, browser/firefox

#2106 feat(chore): more variation options
  src/definitions/collections/form.less
  src/definitions/collections/grid.less
  src/definitions/collections/menu.less
  src/definitions/collections/message.less
  src/definitions/collections/table.less
  src/definitions/elements/button.less
  src/definitions/elements/container.less
  src/definitions/elements/emoji.less
  src/definitions/elements/header.less
  src/definitions/elements/list.less
  src/definitions/elements/segment.less
  src/definitions/elements/step.less
  src/definitions/modules/dropdown.less
  src/definitions/modules/search.less
  src/definitions/modules/sidebar.less
  src/definitions/views/card.less
  src/definitions/views/comment.less
  src/definitions/views/feed.less
  src/definitions/views/item.less
  src/definitions/views/statistic.less
  src/themes/default/globals/variation.variables
Labels: type/feat, lang/css, type/build, state/awaiting-reviews

#2108 fix(modal): respect approve deny callback on js modals
  src/definitions/modules/modal.js
Labels: type/bug, lang/javascript, state/awaiting-reviews, state/awaiting-docs, state/has-docs

#2093 feat(dimmer): use modern blurring to improve performance
  src/definitions/modules/dimmer.less
  src/themes/default/modules/dimmer.variables
Labels: type/feat, lang/css, state/awaiting-reviews, tag/sui-issue

#2109 fix(icon): adjust icons width to match single icon
  src/definitions/elements/icon.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2112 fix(toast): respect approve deny callbacks in actions
  src/definitions/modules/toast.js
Labels: type/bug, lang/javascript, state/awaiting-reviews, state/has-docs

#2111 feat(checkbox): use left/right to switch off/on toggle+slider variant
  src/definitions/modules/checkbox.js
Labels: type/feat, lang/javascript, state/awaiting-reviews

#2088 feat(chore): color list for each component separately
  src/definitions/collections/form.less
  src/definitions/collections/grid.less
  src/definitions/collections/menu.less
  src/definitions/collections/message.less
  src/definitions/collections/table.less
  src/definitions/elements/button.less
  src/definitions/elements/header.less
  src/definitions/elements/icon.less
  src/definitions/elements/input.less
  src/definitions/elements/label.less
  src/definitions/elements/loader.less
  src/definitions/elements/segment.less
  src/definitions/elements/text.less
  src/definitions/modules/checkbox.less
  src/definitions/modules/dropdown.less
  src/definitions/modules/nag.less
  src/definitions/modules/progress.less
  src/definitions/modules/rating.less
  src/definitions/modules/slider.less
  src/definitions/modules/toast.less
  src/definitions/views/card.less
  src/definitions/views/statistic.less
  src/themes/default/globals/variation.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/awaiting-docs, tag/breaking-change

#2091 fix(sidebar): make overflow hidden optional to support sticky
  src/definitions/modules/sidebar.less
Labels: type/bug, lang/css, state/awaiting-reviews, state/awaiting-docs
