Repository fomantic/Fomantic-UI, pull requests merged in 2022-08, with the labels that each got.

#2414 [Dropdown] Fix focus flow when a search dropdown is used from a mobile
  src/definitions/modules/dropdown.js
Labels: type/bug, lang/javascript, state/awaiting-reviews, device/mobile

#2417 feat(transition): firefox needs reattached node to retrieve new anima…
  src/definitions/modules/transition.js
Labels: type/bug, lang/javascript, state/awaiting-reviews, browser/firefox

#2422 fix(form): inverted form labels were black
  src/definitions/collections/form.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2409 feat(dropdown): improve accessibility in relation to search dropdown
  src/definitions/modules/dropdown.js
Labels: type/feat, lang/javascript, state/awaiting-reviews, state/awaiting-changes, state/awaiting-response

#2423 fix(chore): prevent possible xss
  src/definitions/modules/dropdown.js
  src/definitions/modules/embed.js
  src/definitions/modules/modal.js
  src/definitions/modules/rating.js
Labels: lang/javascript, state/awaiting-reviews, type/security

#2426 fix(popup): broken and unnecessary check for string
  src/definitions/modules/popup.js
Labels: type/bug, priority/high, lang/javascript

#2429 fix(modal): avoid propagation of escape to modal
  src/definitions/modules/calendar.js
  src/definitions/modules/checkbox.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/modal.js
  src/definitions/modules/search.js
Labels: type/bug, lang/javascript

#2416 feat(dropdown): optional stuck addition item
  src/definitions/modules/dropdown.less
  src/themes/default/modules/dropdown.variables
Labels: type/feat, lang/javascript, state/has-docs

#2432 fix(chore): identical debug defaults for all modules
  src/definitions/modules/calendar.js
  src/definitions/modules/checkbox.js
Labels: type/feat, lang/javascript

#2434 fix(chore): reuse variables and quicker element access
  src/definitions/behaviors/visibility.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/popup.js
  src/definitions/modules/sticky.js
Labels: type/feat, lang/javascript, state/awaiting-reviews

#2435 fix(search): blur on escape and proper type usage
  src/definitions/modules/search.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2438 fix(chore): forward debug settings to transition on internal use
  src/definitions/modules/accordion.js
  src/definitions/modules/dimmer.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/modal.js
  src/definitions/modules/popup.js
  src/definitions/modules/search.js
  src/definitions/modules/toast.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2437 fix(popup): detailed rtl check
  src/definitions/modules/popup.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2436 fix(sidebar): scrolllock and returnscroll
  src/definitions/modules/sidebar.js
  src/definitions/modules/sidebar.less
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2443 fix(search): missing default easing results in js error
  src/definitions/modules/search.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2442 feat(toast,modal): support short notation $.
  src/definitions/modules/modal.js
  src/definitions/modules/toast.js
Labels: type/feat, lang/javascript, state/awaiting-reviews, state/awaiting-docs
