Repository fomantic/Fomantic-UI, pull requests merged in 2022-10, with the labels that each got.

#2475 fix(dropdown): hide menu on menu search blur
  src/definitions/modules/dropdown.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2480 fix(themes): use only woff files and fix firefox font line gap warning
  src/themes/basic/assets/fonts/icons.eot
  src/themes/basic/assets/fonts/icons.svg
  src/themes/basic/assets/fonts/icons.ttf
  src/themes/basic/elements/icon.variables
  src/themes/default/assets/fonts/brand-icons.eot
  src/themes/default/assets/fonts/brand-icons.svg
  src/themes/default/assets/fonts/brand-icons.ttf
  src/themes/default/assets/fonts/icons.eot
  src/themes/default/assets/fonts/icons.svg
  src/themes/default/assets/fonts/icons.ttf
  src/themes/default/assets/fonts/outline-icons.eot
  src/themes/default/assets/fonts/outline-icons.svg
  src/themes/default/assets/fonts/outline-icons.ttf
  src/themes/default/elements/step.overrides
  src/themes/default/modules/accordion.overrides
  src/themes/default/modules/checkbox.overrides
  src/themes/default/modules/dropdown.overrides
  src/themes/github/assets/fonts/octicons-local.ttf
  src/themes/github/assets/fonts/octicons.svg
  src/themes/github/assets/fonts/octicons.ttf
  src/themes/github/elements/icon.variables
  src/themes/github/modules/dropdown.overrides
  src/themes/material/assets/fonts/icons.eot
  src/themes/material/assets/fonts/icons.svg
  src/themes/material/assets/fonts/icons.ttf
  src/themes/material/elements/icon.variables
  tasks/config/admin/templates/css-package.js
  tasks/config/admin/templates/less-package.js
Labels: type/bug, lang/css, state/awaiting-reviews, browser/firefox

#2474 fix(dropdown): keep original values, also on remove and more fixes
  src/definitions/modules/dropdown.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2477 fix(modal,flyout): dynamic elements did not reference
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2484 feat(form): debug a warning if field identifier is not found
  src/definitions/behaviors/form.js
Labels: type/feat, lang/javascript, state/awaiting-reviews

#2485 fix(dropdown): remove placeholderstyle when same as select text
  src/definitions/modules/dropdown.js
Labels: type/bug, lang/javascript

#2487 fix(sticky): adopt SUI 2.5.0 fixes
  examples/components/sticky-context.html
  src/definitions/modules/sticky.js
  tasks/config/admin/templates/css-package.js
Labels: lang/javascript, type/chore

#2489 feat(form): error instead of debug if field not found
  src/definitions/behaviors/form.js
Labels: type/feat, hacktoberfest-accepted

#2495 fix(rating): partial rating specificity
  src/definitions/modules/rating.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2498 feat(chore): strip/adjust comment headers via config
  tasks/build/css.js
  tasks/build/javascript.js
  tasks/config/defaults.js
  tasks/config/tasks.js
Labels: type/feat, type/build, state/awaiting-reviews, state/awaiting-docs

#2512 fix(chore): support node12 on add
  package.json
  yarn.lock
Labels: type/build

#2516 feat(ci): check node 18 as well
  .github/workflows/ci.yml
Labels: type/ci

#2519 fix(icon): fix lighthouse warning
  src/themes/default/elements/icon.variables
Labels: type/feat, lang/css, state/awaiting-reviews

#2524 chore(dependencies): upgrade to del 6.1.1
  package.json
  yarn.lock
Labels: dependencies

#2525 chore(dependencies): removed unused dependencies
  package.json
  tasks/install.js
  yarn.lock
Labels: dependencies

#2527 feat(build): improve error message for when semantic.json is not found
  tasks/config/user.js
Labels: type/feat, lang/javascript, type/build
