Repository fomantic/Fomantic-UI, pull requests merged in 2022-12, with the labels that each got.

#2580 fix(dropdown): reuse select tabindex
  src/definitions/modules/dropdown.js
Labels: type/bug

#2574 feat(chore): prevent overscrolling
  src/definitions/collections/table.less
  src/definitions/elements/container.less
  src/definitions/elements/segment.less
  src/definitions/modules/dropdown.less
  src/definitions/modules/flyout.less
  src/definitions/modules/modal.less
  src/definitions/modules/search.less
  src/definitions/modules/sidebar.less
  src/themes/default/elements/container.variables
  src/themes/default/elements/segment.variables
  src/themes/default/globals/site.variables
  src/themes/default/globals/variation.variables
Labels: type/feat, lang/css, state/awaiting-reviews, device/mobile

#2587 feat(chore): use modern globalThis
  src/definitions/behaviors/api.js
  src/definitions/behaviors/form.js
  src/definitions/behaviors/state.js
  src/definitions/behaviors/visibility.js
  src/definitions/globals/site.js
  src/definitions/modules/accordion.js
  src/definitions/modules/calendar.js
  src/definitions/modules/checkbox.js
  src/definitions/modules/dimmer.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/embed.js
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
  src/definitions/modules/nag.js
  src/definitions/modules/popup.js
  src/definitions/modules/progress.js
  src/definitions/modules/rating.js
  src/definitions/modules/search.js
  src/definitions/modules/shape.js
  src/definitions/modules/sidebar.js
  src/definitions/modules/slider.js
  src/definitions/modules/sticky.js
  src/definitions/modules/tab.js
  src/definitions/modules/toast.js
  src/definitions/modules/transition.js
Labels: lang/javascript, state/awaiting-reviews, type/chore

#2597 feat(chore): use modern "let" instead of "var" in build scripts
  .eslintrc.js
  gulpfile.js
  tasks/README.md
  tasks/admin/components/create.js
  tasks/admin/components/init.js
  tasks/admin/components/update.js
  tasks/admin/distributions/create.js
  tasks/admin/distributions/init.js
  tasks/admin/distributions/update.js
  tasks/admin/publish.js
  tasks/admin/register.js
  tasks/admin/release.js
  tasks/build.js
  tasks/build/assets.js
  tasks/check-install.js
  tasks/clean.js
  tasks/collections/README.md
  tasks/collections/admin.js
  tasks/collections/docs.js
  tasks/collections/install.js
  tasks/collections/rtl.js
  tasks/collections/various.js
  tasks/config/admin/github.js
  tasks/config/admin/templates/css-package.js
  tasks/config/admin/templates/less-package.js
  tasks/config/npm/gulpfile.js
  tasks/config/project/config.js
  tasks/config/project/install.js
  tasks/config/project/release.js
  tasks/config/tasks.js
  tasks/config/user.js
  tasks/docs/build.js
  tasks/docs/metadata.js
  tasks/docs/serve.js
  tasks/install.js
  tasks/rtl/build.js
  tasks/rtl/watch.js
  tasks/version.js
  tasks/watch.js
  test/meteor/assets.js
  test/modules/module.spec.js
Labels: needs-more-info

#2582 fix(api): explicite url setting should have priority over data url
  src/definitions/behaviors/api.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2614 feat(icon): support custom naming and selector
  src/definitions/elements/icon.less
  src/themes/default/elements/icon.variables
Labels: type/feat, lang/css, type/build, state/awaiting-reviews, state/awaiting-docs

#2615 feat(lint): remove unneeded vendor prefixes
  .stylelintrc.js
  src/definitions/collections/table.less
  src/definitions/elements/image.less
  src/definitions/elements/loader.less
  src/definitions/elements/segment.less
  src/definitions/modules/dimmer.less
  src/definitions/modules/dropdown.less
  src/definitions/modules/flyout.less
  src/definitions/modules/modal.less
  src/definitions/modules/popup.less
  src/definitions/modules/search.less
  src/definitions/modules/sidebar.less
  src/definitions/modules/sticky.less
  src/definitions/views/card.less
  src/themes/pulsar/elements/loader.overrides
Labels: type/feat, lang/css, type/lint

#2604 feat(lint): remove global undefined variable shadow
  .eslintrc.js
  src/definitions/behaviors/api.js
  src/definitions/behaviors/form.js
  src/definitions/behaviors/state.js
  src/definitions/behaviors/visibility.js
  src/definitions/globals/site.js
  src/definitions/modules/accordion.js
  src/definitions/modules/calendar.js
  src/definitions/modules/checkbox.js
  src/definitions/modules/dimmer.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/embed.js
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
  src/definitions/modules/nag.js
  src/definitions/modules/popup.js
  src/definitions/modules/progress.js
  src/definitions/modules/rating.js
  src/definitions/modules/search.js
  src/definitions/modules/shape.js
  src/definitions/modules/sidebar.js
  src/definitions/modules/slider.js
  src/definitions/modules/sticky.js
  src/definitions/modules/tab.js
  src/definitions/modules/toast.js
  src/definitions/modules/transition.js
Labels: lang/javascript, state/awaiting-reviews

#2618 fix(chore): references from SUI to FUI
  examples/fixed.html
  examples/grid.html
  src/definitions/modules/dropdown.js
  src/definitions/modules/popup.js
  src/semantic.less
  tasks/README.md
  tasks/admin/components/create.js
  tasks/build.js
  tasks/build/assets.js
  tasks/build/css.js
  tasks/build/javascript.js
  tasks/collections/docs.js
  tasks/collections/install.js
  tasks/collections/various.js
  tasks/config/admin/release.js
  tasks/config/admin/templates/README.md
  tasks/config/admin/templates/bower.json
  tasks/config/admin/templates/component-package.js
  tasks/config/admin/templates/package.json
  tasks/docs/build.js
  tasks/install.js
  tasks/watch.js
Labels: type/build, type/chore

#2619 fix(chore): remove unnecessary methods and prefixes
  README.md
  src/definitions/behaviors/api.js
  src/definitions/behaviors/form.js
  src/definitions/behaviors/state.js
  src/definitions/behaviors/visibility.js
  src/definitions/globals/site.js
  src/definitions/modules/accordion.js
  src/definitions/modules/calendar.js
  src/definitions/modules/checkbox.js
  src/definitions/modules/dimmer.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/embed.js
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
  src/definitions/modules/nag.js
  src/definitions/modules/popup.js
  src/definitions/modules/progress.js
  src/definitions/modules/rating.js
  src/definitions/modules/search.js
  src/definitions/modules/shape.js
  src/definitions/modules/sidebar.js
  src/definitions/modules/slider.js
  src/definitions/modules/sticky.js
  src/definitions/modules/tab.js
  src/definitions/modules/toast.js
  src/definitions/modules/transition.js
Labels: lang/javascript, type/chore

#2611 feat(lint): add prettier formatter to assert LESS files whitespaces
  .github/workflows/ci.yml
  .prettierrc.js
  .stylelintrc.js
  src/definitions/elements/button.less
  src/definitions/elements/icon.less
  src/definitions/modules/rating.less
  src/definitions/modules/toast.less
  src/definitions/views/card.less
  src/themes/amazon/elements/button.variables
  src/themes/bootstrap3/elements/button.variables
  src/themes/classic/elements/button.variables
  src/themes/classic/views/card.overrides
  src/themes/colored/modules/checkbox.variables
  src/themes/default/collections/form.variables
  src/themes/default/collections/menu.variables
  src/themes/default/collections/message.variables
  src/themes/default/collections/table.variables
  src/themes/default/elements/button.variables
  src/themes/default/elements/flag.variables
  src/themes/default/elements/icon.variables
  src/themes/default/elements/input.variables
  src/themes/default/elements/list.variables
  src/themes/default/elements/placeholder.variables
  src/themes/default/elements/segment.variables
  src/themes/default/elements/step.variables
  src/themes/default/globals/site.variables
  src/themes/default/modules/accordion.variables
  src/themes/default/modules/checkbox.variables
  src/themes/default/modules/dimmer.variables
  src/themes/default/modules/dropdown.variables
  src/themes/default/modules/embed.variables
  src/themes/default/modules/modal.variables
  src/themes/default/modules/progress.variables
  src/themes/default/modules/rating.variables
  src/themes/default/modules/search.variables
  src/themes/default/modules/shape.variables
  src/themes/default/modules/slider.variables
  src/themes/default/views/card.variables
  src/themes/github/collections/form.variables
  src/themes/github/collections/menu.variables
  src/themes/github/collections/message.variables
  src/themes/github/elements/button.variables
  src/themes/github/elements/input.variables
  src/themes/github/modules/dropdown.variables
  src/themes/material/elements/button.variables
  src/themes/material/elements/icon.variables
  src/themes/raised/elements/button.variables
  src/themes/round/elements/button.variables
  src/themes/striped/modules/progress.overrides
Labels: state/on-hold

#2621 feat(build): adjust autoprefixer config to match 2.9.0 browser support
  README.md
  package.json
  tasks/config/tasks.js
  yarn.lock
Labels: type/build, type/chore

#2622 fix(ci): color git diff output
  .github/workflows/ci.yml
Labels: type/ci, type/lint

#2623 fix(icon): unify icon font usage in themes
  src/themes/basic/assets/fonts/icons.woff2
  src/themes/basic/elements/icon.overrides
  src/themes/basic/elements/icon.variables
  src/themes/github/assets/fonts/octicons.woff2
  src/themes/github/elements/icon.overrides
  src/themes/github/elements/icon.variables
  src/themes/material/elements/icon.overrides
  src/themes/material/elements/icon.variables
Labels: type/bug, lang/css, tag/sui-issue

#2625 fix(chore): also use 3 layer logic for colors.less
  src/theme.less
Labels: lang/css, type/build

#2629 fix(chore): dont assign exoego for autoreview anymore
  .github/auto_assign.yml
Labels: type/chore

#2630 fix(chore): fix eslint default config major versions
  .github/workflows/ci.yml
Labels: type/ci, type/lint

#2628 fix(chore): same indent level for multiline const
  tasks/collections/build.js
  tasks/collections/docs.js
  tasks/collections/install.js
  tasks/collections/rtl.js
  tasks/collections/various.js
  tasks/rtl/build.js
Labels: type/chore

#2627 fix(emoji,flag): changing from maxcdn to jsdelivr cdn path
  src/themes/default/elements/emoji.variables
  src/themes/default/elements/flag.variables
  src/themes/twitter/elements/emoji.variables
Labels: type/feat, lang/css, type/chore

#2631 fix(chore): remove old sui v1 unsupported and undocumented code
  src/definitions/behaviors/form.js
  src/definitions/modules/tab.js
  src/themes/default/modules/checkbox.overrides
Labels: type/feat

#2633 fix(form): dynamic validation should't check deleted fields
  src/definitions/behaviors/form.js
Labels: lang/javascript, state/awaiting-reviews, javascript

#2634 fix(dropdown): dont reopen menu on forceselection and search blur
  src/definitions/modules/dropdown.js
Labels: type/bug, lang/javascript
