Repository fomantic/Fomantic-UI, pull requests merged in 2022-09, with the labels that each got.

#2446 fix(chore): fix codeql findings
  src/definitions/behaviors/api.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/modal.js
  src/definitions/modules/popup.js
  src/definitions/modules/progress.js
  src/definitions/modules/search.js
  src/definitions/modules/toast.js
Labels: type/security

#2439 fix(chore): variable declaration and usage fixes and optimization
  src/definitions/behaviors/api.js
  src/definitions/behaviors/form.js
  src/definitions/behaviors/state.js
  src/definitions/behaviors/visibility.js
  src/definitions/globals/site.js
  src/definitions/modules/accordion.js
  src/definitions/modules/calendar.js
  src/definitions/modules/checkbox.js
  src/definitions/modules/dimmer.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/embed.js
  src/definitions/modules/modal.js
  src/definitions/modules/nag.js
  src/definitions/modules/popup.js
  src/definitions/modules/progress.js
  src/definitions/modules/rating.js
  src/definitions/modules/search.js
  src/definitions/modules/shape.js
  src/definitions/modules/sidebar.js
  src/definitions/modules/slider.js
  src/definitions/modules/sticky.js
  src/definitions/modules/tab.js
  src/definitions/modules/toast.js
  src/definitions/modules/transition.js
Labels: type/bug, lang/javascript, state/awaiting-reviews, type/chore

#2433 fix(modal): support context properly
  src/definitions/modules/dimmer.less
  src/definitions/modules/modal.js
  src/definitions/modules/modal.less
Labels: type/bug, lang/css, lang/javascript, state/awaiting-reviews

#2453 refactor(sidebar): remove un-used legacy code
  src/definitions/modules/sidebar.js
Labels: lang/javascript, state/awaiting-reviews, state/has-docs

#2450 fix(toast): enable smooth transition
  src/definitions/modules/toast.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2004 feat(flyout): initial release of flyout module
  src/definitions/modules/flyout.js
  src/definitions/modules/flyout.less
  src/semantic.less
  src/theme.config.example
  src/themes/default/globals/variation.variables
  src/themes/default/modules/flyout.overrides
  src/themes/default/modules/flyout.variables
  tasks/config/admin/release.js
  tasks/config/defaults.js
  tasks/config/project/install.js
Labels: lang/css, lang/javascript, type/discussion, tag/new-component, state/awaiting-reviews, state/on-hold, state/has-docs

#2455 feat(flyout): support short notation $.
  src/definitions/modules/flyout.js
Labels: type/feat, lang/javascript, state/awaiting-reviews, state/awaiting-docs

#2458 fix(sidebar,flyout,modal): missing identical features and fixes
  src/definitions/modules/flyout.js
  src/definitions/modules/flyout.less
  src/definitions/modules/modal.less
  src/definitions/modules/sidebar.js
  src/definitions/modules/sidebar.less
  src/themes/default/globals/variation.variables
  src/themes/default/modules/flyout.variables
  src/themes/default/modules/modal.variables
  src/themes/default/modules/sidebar.variables
Labels: type/feat, lang/css, lang/javascript, state/awaiting-reviews, state/awaiting-docs

#2464 fix(emoji): removed unavailable twemoji resources
  src/themes/default/elements/emoji.variables
  src/themes/joypixels/elements/emoji.variables
  src/themes/twitter/elements/emoji.variables
Labels: lang/css, state/awaiting-reviews, tag/breaking-change

#2466 fix(flag): ensure unique flag and a-z class names
  src/definitions/elements/flag.less
  src/themes/default/elements/flag.variables
Labels: type/bug, lang/css, state/awaiting-reviews

#2470 feat(icon): customizable icons by using maps
  src/definitions/elements/icon.less
  src/themes/default/elements/icon.overrides
  src/themes/default/elements/icon.variables
Labels: type/bug, type/feat, lang/css, state/awaiting-reviews, state/awaiting-docs, tag/breaking-change
