Repository fomantic/Fomantic-UI, pull requests merged in 2022-04, with the labels that each got.

#2297 build(actions): add condition for shouldPublish
  .github/workflows/nightly.yml
  scripts/nightly-version.js
Labels: type/ci

#2296 fix(accordion): prevent ui dropdown icons in titles to animate
  src/definitions/modules/accordion.js
  src/definitions/modules/accordion.less
  src/themes/default/modules/accordion.overrides
Labels: type/bug, lang/css, lang/javascript, state/awaiting-reviews, state/awaiting-docs

#2301 build(dependencies): upgrade semver from 6.3.0 to 7.3.5
  package.json
  yarn.lock
Labels: state/awaiting-reviews, dependencies

#2300 build(dependencies): upgrade mkdirp to from 0.5.6 to 1.0.4
  package.json
  yarn.lock
Labels: state/awaiting-reviews, dependencies

#2305 Fix vertical pointing menu
  src/definitions/collections/menu.less
Labels: type/bug, lang/css

#2316 fix(popup): tooltips cannot contain headers
  src/definitions/modules/popup.less
  src/themes/default/modules/popup.variables
Labels: type/bug, lang/css, state/awaiting-reviews

#2312 fix(button): loading buttons still shows labels
  src/definitions/elements/button.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2311 feat(card): basic variant
  src/definitions/views/card.less
  src/themes/default/globals/variation.variables
  src/themes/default/views/card.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/awaiting-docs

#2309 build(dependencies): require octokit/core to avoid install warning
  package.json
  yarn.lock
Labels: state/awaiting-reviews, dependencies

#2326 fix(dropdown): properly support preventchangetrigger
  src/definitions/modules/dropdown.js
Labels: type/bug, lang/javascript, state/awaiting-reviews, state/awaiting-docs

#2324 feat(calendar): support token dateformats
  src/definitions/modules/calendar.js
Labels: type/feat, lang/javascript, state/awaiting-reviews, state/awaiting-docs, tag/breaking-change

#2280 fix(build): support pnpm folder structure
  tasks/config/project/install.js
Labels: type/build, state/awaiting-reviews, type/upstream

#2317 build(dependencies): update auto-changelog from 1.15.0 to 2.4.0
  package.json
  yarn.lock
Labels: state/awaiting-reviews, dependencies

#2327 fix(slider): support mouse & touch all the time
  src/definitions/modules/slider.js
Labels: lang/javascript, state/awaiting-reviews, device/mobile

#2340 feat(build): require node 12 as minimum
  package.json
Labels: state/awaiting-reviews, type/chore, tag/breaking-change

#2337 fix(emoji,flag): default lineheight should meet text
  src/themes/default/elements/emoji.variables
  src/themes/default/elements/flag.variables
Labels: type/bug, lang/css, state/awaiting-reviews, tag/breaking-change

#2344 fix(dropdown): support preselected on value update for select tag
  src/definitions/modules/dropdown.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2358 fix(api): fix inefficient RegExp that may cause ReDoS
  src/definitions/behaviors/api.js
Labels: lang/javascript, type/security

#2357 fix(emoji): emojies/flags were not properly themeable
  src/definitions/elements/emoji.less
  src/definitions/elements/flag.less
  src/themes/default/assets/images/flags.png
  src/themes/default/elements/emoji.overrides
  src/themes/default/elements/emoji.variables
  src/themes/default/elements/flag.overrides
  src/themes/default/elements/flag.variables
  src/themes/famfamfam/assets/images/flags.png
  src/themes/famfamfam/elements/flag.variables
  src/themes/joypixels/elements/emoji.overrides
  src/themes/joypixels/elements/emoji.variables
  src/themes/twitter/elements/emoji.overrides
  src/themes/twitter/elements/emoji.variables
Labels: type/bug, lang/css, state/awaiting-reviews, tag/breaking-change

#2319 fix(toast): support context setting properly
  src/definitions/modules/toast.js
  src/definitions/modules/toast.less
Labels: type/bug, lang/css, lang/javascript, state/awaiting-reviews

#2360 Use svg icons also for "twitter" theme
  src/themes/twitter/elements/emoji.variables
Labels: type/feat, lang/css

#2336 fix(label): left/right pointing interferes with icon
  src/definitions/elements/label.less
Labels: type/bug, lang/css, state/awaiting-reviews, tag/breaking-change
