Repository fomantic/Fomantic-UI, pull requests merged in 2022-03, with the labels that each got.

#2213 feat(chore): consistent show/hide callbacks
  src/definitions/modules/dimmer.js
  src/definitions/modules/modal.js
  src/definitions/modules/shape.js
  src/definitions/modules/sidebar.js
  src/definitions/modules/transition.js
Labels: type/feat, lang/javascript, state/awaiting-reviews, state/awaiting-docs, tag/sui-issue, tag/breaking-change

#2229 feat(emoji): emoji 13.1 update
  src/themes/default/elements/emoji.overrides
  src/themes/default/elements/flag.overrides
  src/themes/joypixels/elements/emoji.overrides
  src/themes/joypixels/elements/emoji.variables
  src/themes/twitter/elements/emoji.overrides
Labels: type/feat, state/awaiting-reviews, state/has-docs

#2212 fix(modal): close text shadow appeared too early
  src/definitions/modules/modal.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2254 fix(calendar): adjust margin specificity for multimonth
  src/definitions/modules/calendar.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2252 fix(input): date inputs were larger due to icon size
  src/definitions/collections/form.less
  src/definitions/elements/input.less
  src/themes/default/collections/form.variables
Labels: type/bug, lang/css, state/awaiting-reviews

#2253 fix(segment): adjust inverted attached border color specificity
  src/definitions/elements/segment.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2204 fix(dropdown,search): autocomplete affects all chrome based browser
  src/definitions/modules/dropdown.js
  src/definitions/modules/search.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2258 fix(dropdown): legacyEdge cuts search input
  src/definitions/modules/dropdown.js
Labels: type/bug, lang/javascript, state/awaiting-reviews, browser/edge

#2262 fix(theme): material theme changed fontpath in site variables
  src/themes/material/globals/site.variables
Labels: type/bug, lang/css, state/awaiting-reviews

#2259 fix(form): rebind events on dynamic fields
  src/definitions/behaviors/form.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2272 fix(install): dont start interactive script on npm install
  package.json
Labels: type/build, state/awaiting-docs, tag/breaking-change

#2273 build(scripts): reduce nightly publishing
  .github/workflows/nightly.yml
  scripts/nightly-version.js
Labels: type/ci

#2275 fix(calendar): keep whitespace between date and time
  src/definitions/modules/calendar.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2257 feat(api): serializeObject, formdata, files
  src/definitions/behaviors/api.js
Labels: type/feat, lang/javascript, state/awaiting-reviews, state/awaiting-docs

#2279 fix(nightly): get commit hash from npm
  scripts/nightly-version.js
Labels: state/awaiting-reviews, type/ci

#2283 build(scripts): fix nightly exit codes
  .github/workflows/nightly.yml
  package-lock.json
  package.json
  scripts/nightly-version.js
Labels: type/ci

#2284 fix(dropdown): floating shadow and radius on direct child menu only
  src/definitions/modules/dropdown.less
Labels: type/bug, lang/css

#2286 build(workflows): fix nightly build syntax
  .github/workflows/nightly.yml
Labels: type/ci

#2287 feat(chore): move from npm to yarn
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  package-lock.json
  scripts/nightly-version.js
  yarn.lock
Labels: type/build, type/chore

#2293 build(scripts): fix nightly script
  .github/workflows/nightly.yml
  scripts/nightly-version.js
Labels: type/ci

#2294 build(actions): add --tag to publish command
  .github/workflows/nightly.yml
Labels: type/ci
