Repository fomantic/Fomantic-UI, pull requests merged in 2022-05, with the labels that each got.

#2362 fix(chore): eol of text files CRLF to LF
  FAQ.md
  examples/components/button.html
  examples/components/card.html
  examples/components/input.html
  examples/components/menu.html
  examples/components/site.html
  examples/components/table.html
  src/definitions/modules/accordion.less
  tasks/admin/distributions/create.js
  tasks/admin/publish.js
  tasks/admin/release.js
  tasks/build/assets.js
  tasks/build/css.js
  tasks/build/javascript.js
  tasks/check-install.js
  tasks/clean.js
  tasks/collections/README.md
  tasks/collections/admin.js
  tasks/config/admin/oauth.example.js
  tasks/config/admin/templates/composer.json
  tasks/rtl/watch.js
  tasks/version.js
  test/coverage/coverage-PhantomJS 1.9.2 (Linux)-20131014_012621.json
  test/coverage/coverage-PhantomJS 1.9.2 (Linux)-20131014_012811.json
  test/fixtures/accordion.html
  test/fixtures/checkbox.html
  test/fixtures/dropdown.html
  test/fixtures/modal.html
  test/fixtures/popup.html
  test/fixtures/rating.html
  test/fixtures/shape.html
  test/fixtures/sidebar.html
  test/fixtures/tab.html
  test/fixtures/transition.html
  test/fixtures/video.html
  test/helpers/jasmine-jquery.js
  test/helpers/jasmine-sinon.js
  test/helpers/jquery-events.js
  test/helpers/sinon.js
  test/meteor/fonts.js
  test/modules/accordion.spec.js
  test/modules/checkbox.spec.js
  test/modules/dropdown.spec.js
  test/modules/modal.spec.js
  test/modules/module.spec.js
  test/modules/popup.spec.js
  test/modules/search.spec.js
  test/modules/shape.spec.js
  test/modules/sidebar.spec.js
  test/modules/tab.spec.js
  test/modules/transition.spec.js
  test/modules/video.spec.js
Labels: type/feat, lang/css, state/awaiting-reviews

#2331 fix(dropdown): rework touch input handling
  src/definitions/modules/dropdown.js
Labels: type/bug, lang/javascript, state/awaiting-reviews, device/mobile

#2371 fix(dropdown): input width specifitiy was same as form input
  src/definitions/modules/dropdown.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2372 build(deps): bump @actions/core from 1.8.1 to 1.8.2, fixes nightly build
  yarn.lock
Labels: type/dependencies

#2364 fix(button): grey tertiary should not saturate colors
  src/themes/default/globals/site.variables
Labels: type/bug, lang/css, state/awaiting-reviews

#2359 feat(site): offline bundled lato 2.0 and systemfonts, no googleimport by default
  src/theme.less
  src/themes/amazon/globals/site.variables
  src/themes/default/assets/fonts/Lato-Bold.woff
  src/themes/default/assets/fonts/Lato-Bold.woff2
  src/themes/default/assets/fonts/Lato-BoldItalic.woff
  src/themes/default/assets/fonts/Lato-BoldItalic.woff2
  src/themes/default/assets/fonts/Lato-Italic.woff
  src/themes/default/assets/fonts/Lato-Italic.woff2
  src/themes/default/assets/fonts/Lato-Regular.woff
  src/themes/default/assets/fonts/Lato-Regular.woff2
  src/themes/default/assets/fonts/LatoLatin-Bold.woff
  src/themes/default/assets/fonts/LatoLatin-Bold.woff2
  src/themes/default/assets/fonts/LatoLatin-BoldItalic.woff
  src/themes/default/assets/fonts/LatoLatin-BoldItalic.woff2
  src/themes/default/assets/fonts/LatoLatin-Italic.woff
  src/themes/default/assets/fonts/LatoLatin-Italic.woff2
  src/themes/default/assets/fonts/LatoLatin-Regular.woff
  src/themes/default/assets/fonts/LatoLatin-Regular.woff2
  src/themes/default/globals/site.variables
  src/themes/github/globals/site.variables
  src/themes/systemfont/globals/reset.overrides
  src/themes/systemfont/globals/site.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/awaiting-docs, tag/sui-issue, tag/breaking-change

#2375 fix(codeql): fixed codeql findings where applicable
  src/definitions/behaviors/api.js
  src/definitions/behaviors/form.js
  src/definitions/behaviors/state.js
  src/definitions/behaviors/visibility.js
  src/definitions/modules/calendar.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/modal.js
  src/definitions/modules/nag.js
  src/definitions/modules/popup.js
  src/definitions/modules/sidebar.js
  src/definitions/modules/sticky.js
  src/definitions/modules/tab.js
  src/definitions/modules/toast.js
  tasks/build/css.js
  tasks/build/javascript.js
  test/coverage/PhantomJS 1.9.2 (Linux)/index.html
  test/helpers/jasmine-jquery.js
Labels: lang/javascript, state/awaiting-reviews, type/security

#2354 feat(chore): enable codeql action
  .github/codeql/codeql-config.yml
  .github/workflows/codeql.yml
Labels: state/awaiting-reviews, type/chore, type/security

#2378 feat(chore): optional compile for ie specific code
  src/definitions/collections/form.less
  src/definitions/collections/menu.less
  src/definitions/collections/table.less
  src/definitions/elements/input.less
  src/definitions/elements/segment.less
  src/definitions/globals/site.less
  src/definitions/modules/dimmer.less
  src/definitions/modules/dropdown.less
  src/definitions/modules/sticky.less
  src/definitions/views/card.less
Labels: type/feat, lang/css, state/awaiting-docs, browser/edge, browser/ie
