Repository fomantic/Fomantic-UI, pull requests merged in 2023-04, with the labels that each got.

#2752 fix(install): copy overrides.less file on install/update
  tasks/admin/distributions/create.js
  tasks/config/project/install.js
  tasks/install.js
Labels: priority/high, type/build

#2751 fix(formvalidation): support native validation, after submit only
  src/definitions/behaviors/form.js
  src/definitions/collections/form.less
  src/themes/default/globals/variation.variables
Labels: type/bug, lang/javascript, state/awaiting-reviews, state/has-docs

#2753 fix(build): removed never reached error handling
  tasks/config/tasks.js
Labels: type/build

#2669 feat(ci): format LESS files using official prettier
  .github/workflows/ci.yml
  src/themes/amazon/elements/button.variables
  src/themes/bootstrap3/elements/button.variables
  src/themes/chubby/elements/header.variables
  src/themes/default/collections/message.variables
  src/themes/default/elements/button.variables
  src/themes/default/globals/site.variables
  src/themes/default/views/card.variables
  src/themes/github/elements/button.variables
  src/themes/twitter/elements/button.variables
Labels: type/feat, type/chore

#2755 feat(chore): shorten specificity names
  src/definitions/collections/grid.less
  src/definitions/elements/button.less
  src/definitions/elements/input.less
  src/definitions/elements/list.less
  src/definitions/elements/loader.less
  src/definitions/elements/segment.less
  src/definitions/modules/dimmer.less
  src/definitions/modules/dropdown.less
Labels: type/feat, lang/css

#2748 feat(table,segment,container,dropdown,search): resizable scrolling
  src/definitions/collections/table.less
  src/definitions/elements/container.less
  src/definitions/elements/segment.less
  src/definitions/modules/dropdown.less
  src/definitions/modules/modal.less
  src/definitions/modules/search.less
  src/themes/default/collections/table.variables
  src/themes/default/elements/container.variables
  src/themes/default/elements/segment.variables
  src/themes/default/globals/variation.variables
  src/themes/default/modules/dropdown.variables
  src/themes/default/modules/modal.variables
  src/themes/default/modules/search.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/has-docs

#2758 feat(form): optional limit the displayed error messages per field
  src/definitions/behaviors/form.js
Labels: type/feat, state/awaiting-reviews, state/has-docs, tag/sui-issue, javascript

#2759 feat(search): horizontal category variant
  src/definitions/modules/search.less
  src/themes/default/globals/variation.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/has-docs, tag/sui-issue

#2761 feat(item,comment): disabled variants
  src/definitions/views/comment.less
  src/definitions/views/item.less
  src/themes/default/globals/variation.variables
Labels: type/feat, lang/css, state/has-docs

#2765 fix(dropdown): trigger onchange for paste values
  src/definitions/modules/dropdown.js
Labels: type/bug, state/awaiting-reviews, javascript
