Repository fomantic/Fomantic-UI, pull requests merged in 2023-01, with the labels that each got.

#2269 fix(grid): fix stackable nested grid
  src/definitions/collections/grid.less
  src/definitions/modules/popup.less
  src/themes/default/collections/grid.variables
Labels: type/bug, lang/css

#2641 fix(chore): rename to fomantic, update jquery, fix examples
  examples/assets/library/jquery.min.js
  examples/attached.html
  examples/bootstrap.html
  examples/components/button.html
  examples/components/card.html
  examples/components/input.html
  examples/components/menu.html
  examples/components/site.html
  examples/components/sticky-context.html
  examples/components/table.html
  examples/fixed.html
  examples/grid.html
  examples/homepage.html
  examples/login.html
  examples/responsive.html
  examples/sticky.html
  examples/theming.html
  src/definitions/modules/search.js
  tasks/admin/release.js
  tasks/config/admin/templates/package.json
Labels: type/chore

#2639 fix(button): wrong extra inset
  src/definitions/elements/button.less
  src/themes/default/elements/button.variables
Labels: type/bug, lang/css

#2640 fix(icon): removed duplicate icon selectors
  src/themes/default/elements/icon.variables
Labels: type/bug, lang/css

#2644 fix(flyout): content height wrong without header
  src/definitions/modules/flyout.js
  src/definitions/modules/flyout.less
  src/themes/default/modules/flyout.variables
Labels: type/bug, lang/css, state/awaiting-reviews

#2648 feat(search): all and some words for fullTextSearch
  src/definitions/modules/search.js
Labels: type/feat, state/awaiting-reviews, state/has-docs, javascript

#2647 feat(dropdown): dont animate labels when no transition is given
  src/definitions/modules/dropdown.js
Labels: type/feat, state/awaiting-reviews, state/has-docs, javascript

#2654 fix(menu): labeled right menu icon size
  src/definitions/collections/menu.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2652 fix(dropdown): paste values as search query
  src/definitions/modules/dropdown.js
Labels: type/bug, state/awaiting-reviews, javascript

#2575 fix(modal): do autofocus on content change
  src/definitions/modules/flyout.js
  src/definitions/modules/flyout.less
  src/definitions/modules/modal.js
  src/definitions/modules/modal.less
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2668 feat(lint): upgrade prettier to 2.8.3-patched
  .github/workflows/ci.yml
Labels: type/lint

#2672 fix(build): fix path creation to avoid always using default settings
  tasks/config/project/install.js
Labels: type/bug, type/build

#2671 fix(theme): dont conditional import variables to avoid scoping
  src/theme.less
Labels: type/bug, lang/css, type/build, state/awaiting-reviews

#2661 fix(transition): reverted missing invoke method error
  src/definitions/modules/transition.js
Labels: type/bug, state/awaiting-reviews, javascript

#2665 fix(chore): invalid css values
  src/definitions/modules/embed.less
  src/definitions/modules/popup.less
  src/themes/default/collections/menu.variables
  src/themes/default/collections/table.variables
  src/themes/default/elements/segment.variables
  src/themes/default/elements/step.variables
  src/themes/default/globals/site.variables
  src/themes/default/views/item.variables
Labels: type/bug, lang/css, state/awaiting-reviews

#2676 fix(modal): remove active class on hide
  src/definitions/modules/modal.js
  src/definitions/modules/transition.js
Labels: type/bug, lang/javascript

#2679 fix(build): allow gulp install from direct checkout folder
  tasks/install.js
Labels: type/bug, type/build

#2674 fix(modal,flyout): avoid multiple autofocus on show animation
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2662 feat(chore): remove vendor checks
  src/definitions/behaviors/form.js
  src/definitions/modules/accordion.js
  src/definitions/modules/dimmer.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/embed.js
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
  src/definitions/modules/popup.js
  src/definitions/modules/progress.js
  src/definitions/modules/search.js
  src/definitions/modules/shape.js
  src/definitions/modules/sidebar.js
  src/definitions/modules/toast.js
  src/definitions/modules/transition.js
Labels: lang/javascript, state/awaiting-reviews, type/chore

#2656 feat(popup): loading variant
  src/definitions/modules/popup.js
  src/definitions/modules/popup.less
  src/themes/default/modules/popup.variables
Labels: type/feat, lang/javascript, state/has-docs
