Repository fomantic/Fomantic-UI, pull requests merged in 2023-09, with the labels that each got.

#2897 fix(sidebar,flyout): remove unused ios checks
  src/definitions/modules/flyout.js
  src/definitions/modules/sidebar.js
Labels: type/feat, lang/javascript, state/awaiting-reviews, device/mobile, device/tablet

#2901 fix(formvalidation): no error for missing field on autocheck
  src/definitions/behaviors/form.js
  types/fomantic-ui-form.d.ts
Labels: type/bug, state/awaiting-docs, javascript

#2909 feat(header): seamless attached variant
  src/definitions/elements/header.less
  src/themes/default/globals/variation.variables
Labels: type/feat, lang/css, state/awaiting-docs
