Repository fomantic/Fomantic-UI, pull requests merged in 2023-08, with the labels that each got.

#2865 fix(dropdown): remove clearable icon on disabeled or readonly
  src/definitions/modules/dropdown.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2866 feat(calendar): add size variations
  src/definitions/modules/calendar.less
  src/themes/default/globals/variation.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/has-docs

#2878 fix(slider): max value had js floating point issues
  src/definitions/modules/slider.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2883 fix(dropdown): support selection floating or pointing
  src/definitions/modules/dropdown.less
  src/themes/default/modules/dropdown.variables
Labels: type/bug, lang/css, state/awaiting-reviews, state/awaiting-docs

#2894 fix(api): create regexp alias to fix snyk redos false positive
  src/definitions/behaviors/api.js
Labels: type/feat, type/chore, type/security
