Repository fomantic/Fomantic-UI, pull requests merged in 2023-03, with the labels that each got.

#2715 fix(theme): variable inheritance without default imported twice
  src/definitions/collections/breadcrumb.less
  src/definitions/collections/form.less
  src/definitions/collections/grid.less
  src/definitions/collections/menu.less
  src/definitions/collections/message.less
  src/definitions/collections/table.less
  src/definitions/elements/button.less
  src/definitions/elements/container.less
  src/definitions/elements/divider.less
  src/definitions/elements/emoji.less
  src/definitions/elements/flag.less
  src/definitions/elements/header.less
  src/definitions/elements/icon.less
  src/definitions/elements/image.less
  src/definitions/elements/input.less
  src/definitions/elements/label.less
  src/definitions/elements/list.less
  src/definitions/elements/loader.less
  src/definitions/elements/placeholder.less
  src/definitions/elements/rail.less
  src/definitions/elements/reveal.less
  src/definitions/elements/segment.less
  src/definitions/elements/step.less
  src/definitions/elements/text.less
  src/definitions/globals/reset.less
  src/definitions/globals/site.less
  src/definitions/modules/accordion.less
  src/definitions/modules/calendar.less
  src/definitions/modules/checkbox.less
  src/definitions/modules/dimmer.less
  src/definitions/modules/dropdown.less
  src/definitions/modules/embed.less
  src/definitions/modules/flyout.less
  src/definitions/modules/modal.less
  src/definitions/modules/nag.less
  src/definitions/modules/popup.less
  src/definitions/modules/progress.less
  src/definitions/modules/rating.less
  src/definitions/modules/search.less
  src/definitions/modules/shape.less
  src/definitions/modules/sidebar.less
  src/definitions/modules/slider.less
  src/definitions/modules/sticky.less
  src/definitions/modules/tab.less
  src/definitions/modules/toast.less
  src/definitions/modules/transition.less
  src/definitions/views/ad.less
  src/definitions/views/card.less
  src/definitions/views/comment.less
  src/definitions/views/feed.less
  src/definitions/views/item.less
  src/definitions/views/statistic.less
  src/overrides.less
  src/theme.less
Labels: type/bug, lang/css, type/build, type/chore

#2717 fix(dropdown): adjust icon on multiple non selection non search
  src/definitions/modules/dropdown.less
  src/themes/default/modules/dropdown.variables
Labels: type/bug, lang/css, state/awaiting-reviews

#2718 feat(tooltip): match tooltip appearance to default popups
  src/definitions/modules/popup.less
  src/themes/default/modules/popup.variables
Labels: type/feat, lang/css, state/awaiting-reviews

#2711 fix(form): support inline fields group label for required attribute
  src/definitions/behaviors/form.js
  src/definitions/collections/form.less
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2721 fix(slider): also bind events on disabled variant
  src/definitions/modules/slider.js
Labels: type/bug, lang/javascript

#2722 fix(modal): scrolling multple modals positioning
  src/definitions/modules/modal.less
  src/themes/default/modules/modal.variables
Labels: type/bug, lang/css, state/awaiting-reviews

#2725 fix(modal): fade inner dimmer
  src/definitions/modules/modal.js
Labels: type/feat, state/awaiting-reviews, javascript

#2724 fix(modal, flyout): ignore observed non inputs for autofocus
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2726 feat(slider): restrictedLabels, min/maxRange, always ticks, tooltip
  src/definitions/modules/popup.less
  src/definitions/modules/slider.js
Labels: type/feat, lang/javascript, state/awaiting-reviews, state/has-docs

#2729 feat(label): center and bottom ribbon
  src/definitions/elements/label.less
  src/themes/default/elements/label.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/has-docs

#2737 feat(search): onresults callback fromcache
  src/definitions/modules/search.js
Labels: type/feat, lang/javascript, state/awaiting-reviews, state/has-docs

#2734 feat(menu): simpler equal width
  src/definitions/collections/menu.less
Labels: type/feat, lang/css, state/awaiting-reviews, state/has-docs

#2730 fix(segment): piled segments under parent background, inverted variants
  src/definitions/collections/form.less
  src/definitions/elements/segment.less
  src/definitions/modules/toast.less
  src/themes/default/elements/segment.variables
  src/themes/default/globals/site.variables
  src/themes/default/modules/toast.variables
Labels: type/bug, lang/css, state/awaiting-reviews, tag/sui-issue

#2740 feat(segment): loading segment should cover loading spinner
  src/definitions/elements/segment.less
  src/themes/default/elements/segment.variables
Labels: type/bug, lang/css, state/awaiting-reviews, tag/sui-issue

#2741 feat(segment): colored inverted attached segment should not have a bl…
  src/definitions/elements/segment.less
Labels: type/feat, lang/css, state/awaiting-reviews, tag/sui-issue

#2744 feat(flags): add alias for czech
  src/themes/default/elements/flag.variables
Labels: type/feat, lang/css, state/awaiting-reviews

#2743 feat(dropdown): optional keeping the searchterm
  src/definitions/modules/dropdown.js
Labels: type/feat, state/awaiting-reviews, state/has-docs, javascript
