Repository fomantic/Fomantic-UI, pull requests merged in 2023-12, with the labels that each got.

#2948 fix(dropdown): support individual sizing inside forms
  src/definitions/modules/dropdown.less
Labels: type/bug, lang/css, state/awaiting-reviews

#2944 feat(form): support id only input fields for validation
  src/definitions/behaviors/form.js
Labels: type/feat, state/awaiting-reviews, javascript

#2941 feat(form): optional ignore native field validations
  src/definitions/behaviors/form.js
Labels: type/feat, state/awaiting-reviews, state/awaiting-docs, javascript

#2949 feat(form): deprecated and rename empty to notEmpty rule
  src/definitions/behaviors/form.js
Labels: type/feat, state/awaiting-reviews, state/awaiting-docs, javascript

#2959 feat(chore): added asset font license files
  src/themes/basic/assets/fonts/LICENSE.txt
  src/themes/default/assets/fonts/LICENSE_Lato.txt
  src/themes/default/assets/fonts/LICENSE_icons.txt
  src/themes/github/assets/fonts/LICENSE.txt
  src/themes/material/assets/fonts/LICENSE.txt
Labels: state/awaiting-reviews, type/chore

#2946 feat(button): support circular (spaced) button (groups)
  src/definitions/elements/button.less
  src/themes/default/elements/button.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/awaiting-docs

#2958 fix(dropdown): make "set text" work for custom actions
  src/definitions/modules/dropdown.js
Labels: type/bug, state/awaiting-reviews, javascript
