Repository fomantic/Fomantic-UI, pull requests merged in 2023-06, with the labels that each got.

#2813 fix(checkbox): prevent readonly toggle via space
  src/definitions/modules/checkbox.js
Labels: type/bug, lang/javascript, state/awaiting-reviews

#2745 feat(feed): connected, ordered, disabled, divided variant + inverted fix
  src/definitions/elements/icon.less
  src/definitions/elements/list.less
  src/definitions/views/feed.less
  src/themes/default/globals/variation.variables
  src/themes/default/views/feed.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/awaiting-docs

#2818 fix(dropdown): double hide transition breaks upward out
  src/definitions/modules/dropdown.js
Labels: type/bug, state/awaiting-reviews, javascript

#2822 feat(chore): added types definitions
  package.json
  types/fomantic-ui-accordion.d.ts
  types/fomantic-ui-api.d.ts
  types/fomantic-ui-calendar.d.ts
  types/fomantic-ui-checkbox.d.ts
  types/fomantic-ui-dimmer.d.ts
  types/fomantic-ui-dropdown.d.ts
  types/fomantic-ui-embed.d.ts
  types/fomantic-ui-flyout.d.ts
  types/fomantic-ui-form.d.ts
  types/fomantic-ui-modal.d.ts
  types/fomantic-ui-nag.d.ts
  types/fomantic-ui-popup.d.ts
  types/fomantic-ui-progress.d.ts
  types/fomantic-ui-rating.d.ts
  types/fomantic-ui-search.d.ts
  types/fomantic-ui-shape.d.ts
  types/fomantic-ui-sidebar.d.ts
  types/fomantic-ui-slider.d.ts
  types/fomantic-ui-sticky.d.ts
  types/fomantic-ui-tab.d.ts
  types/fomantic-ui-tests.ts
  types/fomantic-ui-toast.d.ts
  types/fomantic-ui-transition.d.ts
  types/fomantic-ui-visibility.d.ts
  types/index.d.ts
  types/tsconfig.json
  types/tslint.json
Labels: type/feat, lang/javascript, type/discussion, type/build, state/awaiting-reviews

#2831 feat(deps): octokit v18 upgrade
  package.json
  yarn.lock
Labels: dependencies

#2833 feat(readme): added ci+ossf badges
  README.md
Labels: type/docs, type/build, type/chore

#2834 chore(docs): added v2.9.x to security support
  SECURITY.md
Labels: type/docs

#2835 chore(docs): remove openbase badge
  README.md
Labels: type/docs

#2838 feat(types): better readability, intellisense improvements, small fixes
  types/fomantic-ui-accordion.d.ts
  types/fomantic-ui-api.d.ts
  types/fomantic-ui-calendar.d.ts
  types/fomantic-ui-checkbox.d.ts
  types/fomantic-ui-dimmer.d.ts
  types/fomantic-ui-dropdown.d.ts
  types/fomantic-ui-embed.d.ts
  types/fomantic-ui-flyout.d.ts
  types/fomantic-ui-form.d.ts
  types/fomantic-ui-modal.d.ts
  types/fomantic-ui-nag.d.ts
  types/fomantic-ui-popup.d.ts
  types/fomantic-ui-progress.d.ts
  types/fomantic-ui-rating.d.ts
  types/fomantic-ui-search.d.ts
  types/fomantic-ui-shape.d.ts
  types/fomantic-ui-sidebar.d.ts
  types/fomantic-ui-slider.d.ts
  types/fomantic-ui-sticky.d.ts
  types/fomantic-ui-tab.d.ts
  types/fomantic-ui-tests.ts
  types/fomantic-ui-toast.d.ts
  types/fomantic-ui-transition.d.ts
  types/fomantic-ui-visibility.d.ts
  types/index.d.ts
Labels: lang/javascript, type/discussion, state/awaiting-reviews

#2841 fix(types): allow JQueryAjaxSettings objects for modules using apiSettings
  types/fomantic-ui-api.d.ts
  types/fomantic-ui-dropdown.d.ts
  types/fomantic-ui-search.d.ts
  types/fomantic-ui-tab.d.ts
Labels: lang/javascript, state/awaiting-reviews, type/types
