Repository fomantic/Fomantic-UI, pull requests merged in 2024-11, with the labels that each got.

#2917 feat(step): circular steps variant
  src/definitions/elements/step.less
  src/themes/default/elements/step.variables
  src/themes/default/globals/variation.variables
Labels: type/feat, lang/css, state/awaiting-docs

#3117 fix(step): color variant specificity
  src/definitions/elements/step.less
Labels: type/bug, lang/css

#3121 fix(calendar): shortyear handling was broken
  src/definitions/modules/calendar.js
Labels: type/bug, javascript
