Repository fomantic/Fomantic-UI, pull requests merged in 2024-12, with the labels that each got.

#3134 feat(ci): upgrade to prettier v3
  .github/workflows/ci.yml
Labels: type/feat, state/awaiting-reviews, type/ci

#3118 Reduce CSS by removing :not() selectors if variation is disabled
  src/definitions/collections/form.less
  src/definitions/collections/grid.less
  src/definitions/collections/menu.less
  src/definitions/collections/table.less
  src/definitions/elements/button.less
  src/definitions/elements/container.less
  src/definitions/elements/divider.less
  src/definitions/elements/emoji.less
  src/definitions/elements/header.less
  src/definitions/elements/icon.less
  src/definitions/elements/input.less
  src/definitions/elements/label.less
  src/definitions/elements/list.less
  src/definitions/elements/loader.less
  src/definitions/elements/segment.less
  src/definitions/elements/step.less
  src/definitions/modules/accordion.less
  src/definitions/modules/calendar.less
  src/definitions/modules/checkbox.less
  src/definitions/modules/dimmer.less
  src/definitions/modules/dropdown.less
  src/definitions/modules/flyout.less
  src/definitions/modules/modal.less
  src/definitions/modules/nag.less
  src/definitions/modules/popup.less
  src/definitions/modules/progress.less
  src/definitions/modules/slider.less
  src/definitions/modules/toast.less
  src/definitions/views/card.less
  src/definitions/views/feed.less
  src/definitions/views/item.less
  src/themes/default/globals/variation.variables
Labels: lang/css, type/build, state/awaiting-reviews

#3138 feat(build): optionally include version in released filename
  tasks/config/project/release.js
  tasks/config/tasks.js
Labels: type/build, state/has-docs

#3133 feat(search): support remove icon
  src/definitions/modules/search.js
  src/definitions/modules/search.less
  src/themes/default/globals/variation.variables
  src/themes/default/modules/search.variables
Labels: type/feat, lang/css, state/awaiting-reviews, state/awaiting-docs, javascript

#3141 feat(calendar): "get date" can return formatted date
  src/definitions/modules/calendar.js
Labels: type/feat, state/has-docs, javascript

#3147 feat(types): format parameters for calendars get date functions
  types/fomantic-ui-calendar.d.ts
Labels: type/types

#3140 feat(build): customizable output filename
  semantic.json.example
  tasks/config/defaults.js
  tasks/config/tasks.js
Labels: type/build, state/has-docs
