Repository fomantic/Fomantic-UI, pull requests merged in 2024-02, with the labels that each got.

#2990 Refactor: Apply border-radius styles to last row of table footer
  src/definitions/collections/table.less
Labels: type/bug, lang/css

#2963 feat(dropdown,search): highlightMatches option
  src/definitions/modules/dropdown.js
  src/definitions/modules/dropdown.less
  src/definitions/modules/search.js
  src/definitions/modules/search.less
  src/themes/default/globals/site.variables
  src/themes/default/globals/variation.variables
  src/themes/default/modules/dropdown.variables
  src/themes/default/modules/search.variables
Labels: type/feat, state/awaiting-reviews, state/awaiting-docs, javascript

#2997 fix(nag): fetch missing event on manual dismiss call
  src/definitions/modules/nag.js
Labels: type/bug, state/awaiting-reviews, javascript

#2995 fix(types): highlightmatches setting
  types/fomantic-ui-dropdown.d.ts
  types/fomantic-ui-search.d.ts
Labels: state/awaiting-reviews, type/types

#2993 fix(dropdown): fix map parameter on htmlentities
  src/definitions/modules/dropdown.js
Labels: type/bug, state/awaiting-reviews, javascript

#2994 fix(dropdown): keep searchterm in menu search
  src/definitions/modules/dropdown.js
Labels: type/bug, state/awaiting-reviews, javascript

#3003 fix(checkbox): disallow keynav on readonly radios
  src/definitions/modules/checkbox.js
Labels: type/bug, state/awaiting-reviews, javascript

#3000 fix(dropdown): support manual removed entries
  src/definitions/modules/dropdown.js
Labels: type/bug, state/awaiting-reviews, javascript

#3004 feat(dropdown): support custom data attributes for items
  src/definitions/modules/dropdown.js
Labels: type/feat, state/awaiting-reviews, state/awaiting-docs
