Repository fomantic/Fomantic-UI, pull requests merged in 2024-03, with the labels that each got.

#2809 feat(embed): add optional alt tag to placeholder
  src/definitions/modules/embed.js
Labels: type/feat, state/awaiting-docs, javascript

#3009 fix(dropdown): clearable icon was missing or misaligned
  src/definitions/modules/dropdown.js
  src/definitions/modules/dropdown.less
Labels: type/bug, lang/css, state/awaiting-reviews

#3014 chore: update funding
  .github/FUNDING.yml
Labels: state/awaiting-reviews, type/chore

#3013 chore: update sponsors
  README.md
Labels: state/awaiting-reviews, type/chore

#3010 fix(core): use scrollbar-width and color on firefox only
  src/definitions/collections/table.less
  src/definitions/globals/site.less
  src/definitions/modules/dimmer.less
  src/definitions/modules/dropdown.less
Labels: type/bug, lang/css, state/awaiting-reviews, browser/chromium

#3011 feat(a11y): support alt attribute for images
  src/definitions/modules/dropdown.js
  src/definitions/modules/search.js
  src/definitions/modules/toast.js
Labels: type/feat, state/awaiting-reviews, state/awaiting-docs, javascript

#3015 fix(formvalidation): improve disabled fields check
  src/definitions/behaviors/form.js
Labels: type/bug, state/awaiting-reviews, javascript
