Repository fomantic/Fomantic-UI, pull requests merged in 2025-05, with the labels that each got.

#3269 change(modal): allows image description flexbox to take available space
  src/definitions/modules/modal.less
Labels: type/bug, lang/css

#3273 fix(modal): Change default min-width value of description flexbox to 'auto'
  src/themes/default/modules/modal.variables
Labels: type/bug, lang/css

#3267 fix(button): stackable needs fluid for 100% width
  src/definitions/elements/button.less
Labels: type/bug, lang/css, state/awaiting-docs, tag/breaking-change

#3257 fix(table): inverted basic table background
  src/definitions/collections/table.less
Labels: type/bug, lang/css, state/awaiting-reviews
