Repository fomantic/Fomantic-UI, pull requests merged in 2025-03, with the labels that each got.

#3181 fix(deps): drop node 12-16, upgrade to zero issues, clean audit
  .github/workflows/ci.yml
  package.json
  tasks/config/tasks.js
  yarn.lock
Labels: type/build, type/ci, dependencies

#3192 feat(chore): proof reading fixes
  src/README.md
  src/definitions/behaviors/api.js
  src/definitions/behaviors/form.js
  src/definitions/behaviors/state.js
  src/definitions/behaviors/visibility.js
  src/definitions/collections/form.less
  src/definitions/modules/calendar.js
  src/definitions/modules/dimmer.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/embed.js
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
  src/definitions/modules/nag.js
  src/definitions/modules/popup.js
  src/definitions/modules/progress.js
  src/definitions/modules/search.js
  src/definitions/modules/shape.js
  src/definitions/modules/sidebar.js
  src/definitions/modules/slider.js
  src/definitions/modules/slider.less
  src/definitions/modules/sticky.js
  src/definitions/modules/tab.js
  src/definitions/modules/toast.js
  src/definitions/modules/transition.js
  src/themes/default/modules/slider.variables
Labels: state/awaiting-reviews, type/chore, tag/breaking-change

#3193 fix(task): deps changes, cleanup, windows+gulp fixes
  package.json
  tasks/README.md
  tasks/admin/components/create.js
  tasks/admin/components/init.js
  tasks/admin/components/update.js
  tasks/admin/distributions/create.js
  tasks/admin/distributions/init.js
  tasks/admin/distributions/update.js
  tasks/admin/publish.js
  tasks/admin/register.js
  tasks/admin/release.js
  tasks/build/css.js
  tasks/build/javascript.js
  tasks/check-install.js
  tasks/clean.js
  tasks/collections/admin.js
  tasks/collections/docs.js
  tasks/config/admin/github.js
  tasks/config/admin/templates/README.md
  tasks/config/admin/templates/bower.json
  tasks/config/admin/templates/composer.json
  tasks/config/project/config.js
  tasks/config/project/install.js
  tasks/config/project/release.js
  tasks/config/tasks.js
  tasks/config/user.js
  tasks/docs/metadata.js
  tasks/docs/serve.js
  tasks/install.js
  tasks/rtl/watch.js
  tasks/watch.js
  yarn.lock
Labels: type/feat, state/awaiting-reviews, type/chore, dependencies

#3191 feat(chore): new default settings monthFirst and preserveHTML
  src/definitions/modules/calendar.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
  src/definitions/modules/search.js
  src/definitions/modules/toast.js
  types/fomantic-ui-calendar.d.ts
  types/fomantic-ui-dropdown.d.ts
  types/fomantic-ui-flyout.d.ts
  types/fomantic-ui-modal.d.ts
  types/fomantic-ui-search.d.ts
  types/fomantic-ui-toast.d.ts
Labels: state/awaiting-reviews, state/awaiting-docs, tag/breaking-change, javascript

#3183 feat(chore): remove ie11 and old edge related code
  README.md
  src/definitions/collections/form.less
  src/definitions/collections/menu.less
  src/definitions/collections/table.less
  src/definitions/elements/input.less
  src/definitions/elements/segment.less
  src/definitions/globals/site.less
  src/definitions/modules/dimmer.less
  src/definitions/modules/dropdown.js
  src/definitions/modules/dropdown.less
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
  src/definitions/modules/modal.less
  src/definitions/modules/search.less
  src/definitions/modules/sidebar.js
  src/definitions/modules/toast.less
  src/definitions/modules/transition.js
  src/themes/basic/assets/fonts/icons.woff
  src/themes/basic/elements/icon.variables
  src/themes/default/assets/fonts/Lato-Bold.woff
  src/themes/default/assets/fonts/Lato-BoldItalic.woff
  src/themes/default/assets/fonts/Lato-Italic.woff
  src/themes/default/assets/fonts/Lato-Regular.woff
  src/themes/default/assets/fonts/LatoLatin-Bold.woff
  src/themes/default/assets/fonts/LatoLatin-BoldItalic.woff
  src/themes/default/assets/fonts/LatoLatin-Italic.woff
  src/themes/default/assets/fonts/LatoLatin-Regular.woff
  src/themes/default/assets/fonts/brand-icons.woff
  src/themes/default/assets/fonts/icons.woff
  src/themes/default/assets/fonts/outline-icons.woff
  src/themes/default/collections/table.variables
  src/themes/default/elements/icon.variables
  src/themes/default/globals/site.variables
  src/themes/github/assets/fonts/octicons.woff
  src/themes/github/elements/icon.variables
  src/themes/material/assets/fonts/icons.woff
  src/themes/material/elements/icon.variables
  tasks/config/admin/templates/css-package.js
  tasks/config/tasks.js
Labels: lang/css, type/build, state/awaiting-reviews, state/awaiting-docs, tag/breaking-change, javascript

#3185 feat(dropdown): support compact without selection
  src/definitions/modules/dropdown.less
Labels: type/feat, lang/css, state/awaiting-reviews

#3182 feat(docs): adjust some core info
  CONTRIBUTING.md
  FAQ.md
  ROADMAP.md
  SECURITY.md
Labels: type/docs

#3190 feat(chore): remove deprecated features
  src/definitions/behaviors/form.js
  src/definitions/collections/grid.less
  src/definitions/elements/segment.less
  src/definitions/modules/checkbox.js
  src/theme.less
  src/themes/default/collections/grid.variables
  src/themes/default/globals/variation.variables
  types/fomantic-ui-form.d.ts
Labels: lang/css, state/awaiting-reviews, state/awaiting-docs, tag/breaking-change, javascript

#3202 feat(dropdown,search): settings as templates parameter
  src/definitions/modules/dropdown.js
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
  src/definitions/modules/search.js
  src/definitions/modules/toast.js
  types/fomantic-ui-dropdown.d.ts
  types/fomantic-ui-search.d.ts
Labels: state/awaiting-reviews, state/awaiting-docs, tag/breaking-change, javascript

#3198 feat(deps): remove wrench
  package.json
  tasks/config/defaults.js
  tasks/config/project/install.js
  tasks/install.js
  yarn.lock
Labels: type/build, state/awaiting-reviews, dependencies

#3209 feat(dropdown, search): remove support check for ignoreDiacritics
  src/definitions/modules/dropdown.js
  src/definitions/modules/search.js
Labels: type/feat, state/awaiting-reviews, tag/breaking-change, javascript

#3215 Refactor HTML escape functions
  src/definitions/modules/dropdown.js
  src/definitions/modules/embed.js
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
  src/definitions/modules/popup.js
  src/definitions/modules/rating.js
  src/definitions/modules/search.js
  src/definitions/modules/toast.js
Labels: type/feat, javascript

#3217 fix(dropdown): API query does not run when the dropdown is opened by pressing the down arrow key
  src/definitions/modules/dropdown.js
Labels: type/bug, javascript

#2584 Replace "var" declarations with "let"
  .eslintrc.js
  src/definitions/behaviors/api.js
  src/definitions/behaviors/form.js
  src/definitions/behaviors/state.js
  src/definitions/behaviors/visibility.js
  src/definitions/globals/site.js
  src/definitions/modules/accordion.js
  src/definitions/modules/calendar.js
  src/definitions/modules/checkbox.js
  src/definitions/modules/dimmer.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/embed.js
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
  src/definitions/modules/nag.js
  src/definitions/modules/popup.js
  src/definitions/modules/progress.js
  src/definitions/modules/rating.js
  src/definitions/modules/search.js
  src/definitions/modules/shape.js
  src/definitions/modules/sidebar.js
  src/definitions/modules/slider.js
  src/definitions/modules/sticky.js
  src/definitions/modules/tab.js
  src/definitions/modules/toast.js
  src/definitions/modules/transition.js
Labels: type/feat, lang/javascript, type/ci, tag/breaking-change

#3220 fix(docs): adjust minimum ios and android versions
  README.md
Labels: type/docs

#3225 feat(chore): remove check for mutationoberserver support
  src/definitions/behaviors/visibility.js
  src/definitions/modules/accordion.js
  src/definitions/modules/calendar.js
  src/definitions/modules/checkbox.js
  src/definitions/modules/dropdown.js
  src/definitions/modules/flyout.js
  src/definitions/modules/modal.js
  src/definitions/modules/popup.js
  src/definitions/modules/sticky.js
Labels: lang/javascript, type/chore

#3221 feat(emoji): new default for variationEmojiNoColons is false
  src/themes/default/globals/variation.variables
Labels: lang/css, type/build, state/awaiting-reviews, state/awaiting-docs, tag/breaking-change

#3201 feat(menu): rename tabular to tabbed
  examples/attached.html
  examples/components/menu.html
  src/definitions/collections/menu.less
  src/themes/chubby/collections/menu.variables
  src/themes/default/collections/menu.variables
  src/themes/default/globals/variation.variables
Labels: lang/css, state/awaiting-reviews, state/awaiting-docs, tag/breaking-change
